### PR TITLE
OpenCL runtime environment is no longer required with --keyspace option

### PR DESCRIPTION
**Pull request by matrix**
Solved issue #84

### CODE REVIEW

**Comment by philsmd** [comment]
It doesn't look like it works for me:
strace ./oclHashcat --keyspace -a 3 ?a?a?a?a?a?a?a?a 2>&1 | egrep 'libamd|libOpenCL'

As far as I understood, there should be no requirement for loading those (and maybe other) libs when running with --keypace option. Your fix doesn't change this.

**Comment by matrix** [comment]
Check here

http://pastebin.com/pZNagJ1P

**Comment by philsmd** [comment]
If I try without the libraries I get this error:
./oclHashcat --keyspace -a 3 ?a?a?a?a?a?a?a?a
./oclHashcat: error while loading shared libraries: libOpenCL.so.1: cannot open shared object file: No such file or directory

This is what the issue #84 is trying to fix (in my opinion), i.e. using --keyspace also when the libraries are not present

**Comment by matrix** [comment]
You can't never build without OpenCL library but now you can use --keyspace switch without have a compatible hardware.
I think is the max we can do without write another standalone tool for calculate only the keyspace.

**Comment by philsmd** [comment]
the tool for calculating the --keyspace already exist in hashcat-utils: https://github.com/hashcat/hashcat-utils/blob/master/src/keyspace.c
But again the goal that issue #84 should solve is to allow the user to run --keyspace without loading those libraries that are not needed to show the --keyspace value.

**Comment by matrix** [comment]
I read that in original issue description:

"I would like to propose that when using [the] `keyspace' flag, oclHashcat should simply calculate & print the keyspace, then exit. No OpenCL checks or device enumeration should be performed, as OpenCL runtime & devices are not required for this functionality."

If you don't like that talk also with others team member about closing this pull request and also issue 84.

**Comment by jsteube** [comment]
I think what we really need to make it "perfect" is a dlopen() loader for OpenCL as we already do for ADL and NVML. That would be great!

**Comment by magnumripper** [comment]
That is very tedious to achieve but obviously has some advantages. Hashkill does that. I had a look (long ago) at nicking that code but opted not to.

**Comment by matrix** [comment]
Very tedious but i like @jsteube idea.
Work in progress

**Comment by matrix** [comment]
@jsteube look this patch ;)

**Comment by jsteube** [comment]
WOW! Good work, you must have been busy. I'll merge it but maybe rename some variable names.

**Comment by jsteube** [comment]
Don't forget to create a PR for it

**Pull request closed without merging**
