### PR TITLE
Declare phony targets in Makefile

### PR DESCRIPTION
**Pull request by ventaquil**
According to [GNU `make` Phony Targets](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html) here you have a little change in `Makefile`.

### CODE REVIEW

**Comment by philsmd** [comment]
Hey @ventaquil , was this closed on accident or did you intent closing this pull request.

I think that it could make sense, even though it's not very, very important or is it ? it for sure doesn't really make things fail, but I see some advantages, like cleaner "Makefile target list" etc

**Comment by ventaquil** [comment]
Hey @philsmd - I broke this PR because I tried to make another one (#2585)  and force pushed to `master` branch 😢

I think it's not very important - it's more like "nice-to-have" feature.

**Comment by ventaquil** [comment]
I thought about rewrite some install targets like

```makefile
install_hashcat: $(HASHCAT_FRONTEND)
	$(INSTALL) -m 755 -d                                                    $(DESTDIR)$(INSTALL_FOLDER)
	$(INSTALL) -m 755 $(HASHCAT_FRONTEND)                                   $(DESTDIR)$(INSTALL_FOLDER)/
```

into

```makefile
install_hashcat: $(DESTDIR)$(INSTALL_FOLDER)/$(HASHCAT_FRONTEND)

$(DESTDIR)$(INSTALL_FOLDER):
	$(INSTALL) -m 755 -d $(DESTDIR)$(INSTALL_FOLDER)

$(DESTDIR)$(INSTALL_FOLDER)/$(HASHCAT_FRONTEND): $(DESTDIR)$(INSTALL_FOLDER) $(HASHCAT_FRONTEND)
	$(INSTALL) -m 755 $(HASHCAT_FRONTEND) $(DESTDIR)$(INSTALL_FOLDER)/
```

It can work better when you use `--jobs` flag. An additional advantage is that after some change only related targets are executed.

What do you think about that @philsmd?

**Comment by philsmd** [comment]
not sure if it really makes sense for our use case. It seems to be just much longer and more difficult to understand/read.
We try to keep things easy to read and with as little code/lines as possible, if it still works and has only minor disadvantages/cons.

The problem is what if we need to add dozens of more lines to `install_hashcat`, it would just make the `Makefile` very long with this alternative approach (even though it might be a better approach/design and more correct in terms of Makefile targets etc).

I wouldn't really be against any such change if devs decide to use this approach, but in my opinion it's just a little bit more difficult to understand/read compared to the list of `$(INSTALL)` one after the other.

Maybe other devs have a completely different opinion about this, dunno

**Pull request merged**
