### PR TITLE
Cosmetic fix for types.h

### PR DESCRIPTION
**Pull request by matrix**

### CODE REVIEW

**Comment by philsmd** [comment]
this commit is evil !

Labeling a commit as "cosmetic fix", providing no description ("No desciption provided." is the message of this pull request), but changing the restore file format in a very significant way such that it breaks --restore support of .restore files without updating the file format (https://hashcat.net/wiki/doku.php?id=oclHashcat#parsing_the_restore-file ) and warning the user about the changes in docs/changes.txt ... is something we should **not** tolerate at all.
Maybe it was "just a mistake", but as I said it broke a lot of things (analyze_hc_restore, some 3rd-party wrappers, the wiki documentation, ... etc.).

I also had to **troubleshoot**/debug this a little bit until I figured out that the restore format was changed without any notice.

Can you (@gm4tr1x) please explain how this could happen at all, what were the reasons for this significant change, why we really need it and most of all why you did change the restore file format without giving any meaningful explanation (or no explanation at all)?

P.S. the change I am speaking about is  "char cwd[256]" -> "char cwd[1024]" of struct restore_data_t in types.h

Thx

**Comment by matrix** [comment]
@philsmd, if you want some details send me a mail or write me in private dev channel, as all the other team member do.

Bye.

**Comment by magnumripper** [comment]
> if you want some details send me a mail or write me in private dev channel

So much for open source. Oh well.

**Comment by matrix** [comment]
@magnumripper if you want same details tell me.
We prefer speak in private when is possible (tell @jsteube, @epixoip, @Xanadrel, @dropdeadfu).
But if you are curious the response is around the getcwd() function usage.

@philsmd, free to change back cwd[1024] to cwd[256].
Better than tell me some details no?

If I found a bug I usually proceed with the fix, not with 3000 comments on github.
Thats all and sorry for the "evil commit" ...

**Comment by magnumripper** [comment]
Of course you should discuss some things OOB but if you keep the rationale for design decisions secret it only makes it harder for anyone outside your little club to contribute code. I can't see the upside, but never mind me.

**Comment by matrix** [comment]
@magnumripper if I found something bad in @jsteube commits or something I like write @jsteube in private and talk with him about what I found.
I'm coding with @jsteube for years without any public discussion and the quality of our code now is visible to all. 

It's sufficient as explanation ?

**Comment by epixoip** [comment]
I understand your concern @magnumripper, but I think you're conflating "open source" with "community-driven." Hashcat is obviously open source; however, while contributions from the community are appreciated, Hashcat is _not_ a community-driven project.

The Hashcat development model is top-down, with @jsteube functioning as the BDFL and the core team members (@philsmd, @gm4tr1x, @Xanadrel, @dropdeadfu, and myself) functioning as the project directors. Control of the development process and decision making authority are retained by the group of aforementioned individuals; they have neither been passed down nor delegated to the community. So it is only natural that this "little club" would have a place to meet and discuss the project in private.

The upside of this model should be quite obvious, magnum... please do not make me state it.

**Pull request merged**
