### PR TITLE
Skip unstable hash modes (OSX only)

### PR DESCRIPTION
**Pull request by matrix**
If '--force' is not set, we proceed to excluding unstable hash modes
because some of them cause segfault or inconclusive attack.

In that way if you run an attack using all device types (ex: using -D 1,2)
will be skipped only the device+hashmodes unsupported combo.
Example

```
$ ./hashcat -b -m 14100 -D1,2
hashcat (v3.10-755-g28ec87a) starting in benchmark mode...

OpenCL Platform #1: Apple
=========================
* Device #1: Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz, 2047/8192 MB allocatable, 4MCU
* Device #2: Iris, 384/1536 MB allocatable, 40MCU

Hashtype: 3DES (PT = $salt, key = $pass)

* Device #2: hashmode 14100 is unstable for this Apple GPU Device, skipping (use --force to override)

Speed.Dev.#1.....:  5602.5 kH/s (5988.88ms)
Speed.Dev.#*.....:  5602.5 kH/s

Started: Thu Nov 17 23:32:49 2016
Stopped: Thu Nov 17 23:32:57 2016
```
Following the list of unstable modes:

- shared (cpu & gpu)
1500, 3000, 14000

- gpu only
14100

- cpu only
3200, 9000

### CODE REVIEW

**Comment by jsteube** [comment]
There's no code to unset device_param->skipped = true after that specific hash-mode, I'll fix

**Comment by matrix** [comment]
I do not understand but I trust you :P

**Comment by jsteube** [comment]
I'll try to rephrase. Problem only occurs when not specifying -m in combination with -b. 

If we set skipped = true, the -b mode will skip all hash-modes after the unstable hash-modes because skipped is never set back to false for the stables hash-modes. 

After fix, it will look like this:

```
root@ht:~/hashcat# ./hashcat -b --mac
# hashcat (v3.10-757-g72e39a7+)
1:900:1189:2700:7094485215
1:0:1189:2700:3842697205
1:5100:1189:2700:2374526360
1:100:1189:2700:1307206881
1:1400:1189:2700:464342317
1:10800:1189:2700:149045586
1:1700:1189:2700:152280385
1:5000:1176:2700:138155729
1:10100:1189:2700:4513826492
1:6000:1189:2700:745232064
1:6100:1189:2700:41219878
1:6900:1189:2700:40451511
1:11700:1189:2700:8174836
1:11800:1189:2700:8178862
* Device #1: skipping unstable hash-mode 14000 for this specific device, use --force to override
* Device #1: skipping unstable hash-mode 14100 for this specific device, use --force to override
1:400:1189:2700:992828
1:8900:1189:2700:124326
1:11900:1189:2700:1086006
1:12000:1189:2700:522775
```

**Comment by matrix** [comment]
Ok, now I understand.
Can you fix it?

**Comment by jsteube** [comment]
Yes, working on it

**Comment by jsteube** [comment]
Please verify https://github.com/hashcat/hashcat/commit/105513e3077d09126d5e0a6fef52998ba35a0909

**Pull request merged**
