### PR TITLE
const and char fixes

### PR DESCRIPTION
**Pull request by neheb**
If compiling in C++ mode, the first two commits are bugfixes.

The last one is not.

### CODE REVIEW

**Review by jtojanen — COMMENTED** [review]
You should know that AUTO is GCC only, but GCC is only one compiler.. Please follow contributing guidelines and GNU99 standard. Revert adae3ad and I think this should be accepted.

**Comment by neheb** [comment]
Works with clang too.

**Comment by neheb** [comment]
Note that hashcat is built with gnu99. Extensions should be fine.

**Comment by jtojanen** [comment]
> Note that hashcat is built with gnu99. Extensions should be fine.

I agree with you about const correctness, but you could have resolved these as easily by replacing them with "const char *const" instead of using auto extension.

**Comment by neheb** [comment]
right. My reasoning is that auto is easier to read as it's shorter.

**Comment by jtojanen** [comment]
> right. My reasoning is that auto is easier to read as it's shorter.

True. Counterargument is that "const char *const" retains all type information, constness of data and pointer.

**Comment by jsteube** [comment]
Could we replace the "const AUTO" with "const char *const" instead?

**Comment by neheb** [comment]
Redone. Removed AUTO.

**Comment by jsteube** [comment]
Many thanks!

**Pull request merged**
