### PR TITLE
Adding support for SM3

### PR DESCRIPTION
**Pull request by Zgzorx**
Issue : https://github.com/hashcat/hashcat/issues/3340

We (@loukabvn and I) are adding SM3 a0 a1 a3 pure and optimized.

Perl is lacking SM3 implementation so we are discussing the way for the modules to be tested.

### CODE REVIEW

**Comment by Zgzorx** [comment]
Has mentionned previously, Perl can't handle SM3, what kind of test can we give ?

**Comment by jsteube** [comment]
Wow, that's really cool. Algorithm reminds me a lot on SHA256 :)
Regarding the perl module, it's optional. But maybe you can use SHA256 implementation in perl as template.

**Comment by jsteube** [comment]
Let me know when you think it's ready for merge. Please rename to 31100.

**Comment by Zgzorx** [comment]
I used Python to run my own tests and everything seems in order. Note that I don't have access to any CUDA capable chip and @loukabvn is unavailable for a week. Could you run a benchmark please ? If it passes, I think it's ready for merge.

**Comment by jsteube** [comment]
I manually checked -a 0 and -a 3 and it worked fine.

**Comment by jsteube** [comment]
Many thanks for contribution, this is great work!

**Comment by jsteube** [comment]
@Zgzorx @loukabvn Please see commit: https://github.com/hashcat/hashcat/commit/9acfc26d818dc3e2f2a7a00a850e09ca0da67657

It's just a tiny optimization (on my 2080ti from 6.6GH/s to 6.9GH/s), but I think it can be replicated to other optimized kernels (single hash only).
Just in case you enjoy optimizing same way I do :)

**Pull request merged**
