### PR TITLE
Adding Blake2s-256

### PR DESCRIPTION
**Pull request by Zgzorx**
Issue : https://github.com/hashcat/hashcat/issues/3414

We are adding Blake2s-256 a0, a1 and a3 pure and optimized

Note that we chose 35000 arbitrarily and we are waiting for a given number to change it

### CODE REVIEW

**Comment by Zgzorx** [comment]
I a bit confused because this is my first Pull Request ever. I would like to add that @loukabvn is a collaborator on this work. Is there any way to add him as participant ?

**Comment by jsteube** [comment]
Very good work! Could you please rename the hash-mode from 35000 to 31000?

**Comment by jsteube** [comment]
On my system (CUDA), I'm getting the following error:

```
$ ./hashcat -b -m 35000
/root/git/hashcat/OpenCL/inc_hash_blake2s.cl(75): error: expression must have class type but it has type "u64"
```

**Comment by Zgzorx** [comment]
> Very good work! Could you please rename the hash-mode from 35000 to 31000?

Should be done

**Comment by Zgzorx** [comment]
> On my system (CUDA), I'm getting the following error:
> 
> ```
> $ ./hashcat -b -m 35000
> /root/git/hashcat/OpenCL/inc_hash_blake2s.cl(75): error: expression must have class type but it has type "u64"
> ```

Couldn't test it on GPU yet, we will try to get one soon and fix this.

**Comment by loukabvn** [comment]
Hi, I work on this with @Zgzorx and the last commit should fix the problem. We test it on both CPU (Intel Graphics 620) and GPU (GTX 1050) and it seems to works with CUDA and OpenCL.

**Comment by jsteube** [comment]
Really nice work, all tests passed. Many thanks for the contribution!

**Comment by jsteube** [comment]
@Zgzorx @loukabvn please notice https://github.com/hashcat/hashcat/commit/4fe37f5445b6c87f83f624b84acb1186580f7d2b

**Comment by Zgzorx** [comment]
> @Zgzorx @loukabvn please notice [4fe37f5](https://github.com/hashcat/hashcat/commit/4fe37f5445b6c87f83f624b84acb1186580f7d2b)

I think that's on me, sorry

**Comment by jsteube** [comment]
No need to apologize. Thanks for the contribution, that's what counts.

**Pull request merged**
