### PR TITLE
About issue #120 and issue #63

### PR DESCRIPTION
**Pull request by matrix**
Added support for build without ADL/NVML/NVAPI (issue #120).
Added support for build OSX native binaries (issue #63).

I do not think it is useful split into 2 PR because each one depends on the other.

### CODE REVIEW

**Comment by matrix** [comment]
Thanks bro ;)

**Comment by magnumripper** [comment]
Good stuff! Works fine on my macbook.

**Comment by matrix** [comment]
Thanks for the test :)

**Comment by philsmd** [comment]
Can be merged!

(BTW: it would be great if you @gm4tr1x update #63 (I guess we shouldn't close it yet) and mention the progress, what is currently not working yet e.g. --benchmark, for which algorithm the tests currently fail and also most importantly why you had to change some parts in this particular manner, e.g. why there is no --cpu-affinity etc. I mean, this are very critical changes and imply that we can't tell the users @ forum/irc that they can "just use --cpu-affinity" to just mention an example. We need some clues/documentation why it was changed like this and what is still missing).
Thx

**Pull request merged**
