### PR TITLE
Added Linux Kernel Crypto API (2.4) KPA

### PR DESCRIPTION
**Pull request by matrix**
See #1730 for details.

### CODE REVIEW

**Comment by jsteube** [comment]
While the implementation is based on the original issue description I believe there's a better test possible.

It limits the useability of the plugin to filesystems which actually create 16 zero bytes at that specific position.

I suggest to modify the plugin to allow giving both IV and PT.

We have IV:

```
03000000000000000000000000000000
```

I'm just guessing here, but I think this value is the result of the sector count (as u32 values in BE byte order). Sector size usually is 512.

so 0x600 = 1536 = 1536 / 512 = 3

We have PT:

```
00000000000000000000000000000000
```

I had this verified. For the filesystems I tried this section was set to zero. So this is OK.

This is why we see in the kernel (AES):

```
const u32 iv[4] = { 0x03000000, 0x00000000, 0x00000000, 0x00000000 };
```

It is the already precomputed PT ^ IV values.

Right now a hash of the original implementation looked like this:

```
$cryptoapi$9$2$d1d20e91a8f2e18881dc79369d8af761
```

And should be:

```
$cryptoapi$9$2$03000000000000000000000000000000$00000000000000000000000000000000$d1d20e91a8f2e18881dc79369d8af761
```

Inside the module, we can precompute PT ^ XOR and then convert to the byte order based on hash and cipher selected and store it in salt->salt_buf.


---

There's a cryptoapi2hashcat extraction tool missing. 

For documentation reasons: You need to extract the 16 bytes at 0x600 from the encrypted block device / file.

```
 cryptsetup create --cipher  aes-cbc-plain --key-size 256 --hash ripemd160 crypted disk.raw
```

```
$ dd if=disk.raw skip=1536 bs=1 count=16 status=none | xxd     
00000000: d1d2 0e91 a8f2 e188 81dc 7936 9d8a f761  ..........y6...a
```

```
$cryptoapi$9$2$d1d20e91a8f2e18881dc79369d8af761
```

The user needs to set the hash, cipher and keysize (see src/modules/module_14500.c for supported list)

The 9 = RipeMD160 + AES
The 2 = 256 bit key

---

We really need the missing perl unit test module. The problem here is that hashcat can not load multiple kernels dynamically.

It should be enough to have at least RipeMD160 + AES in the unit test.

In addition, there should be a full example hashlist to test other combinations than AES and RipeMD160. The different combinations of hashes and ciphers with mixed types of byte order can easily confuse a programmer. 

Please add a full list for each kernel type, see tools/tc_tests/ as an example.

---

The _a3 kernel all make use of NEW_SIMD_CODE while the cipher do not support vector data types. 

You need to comment them out the same way you did in _a0 and _a1 and use inc_scalar.cl instead of inc_simd.cl. Of course also need to change COMPARE_S_SIMD to COMPARE_S_SCALAR.

---

The kernels can be heavily optimized with a simple trick. Instead of 

```
ripemd160_update (&ctx, padding, 1);
```

We can do:

```
ctx.w0[0] = 'A';
ctx.len = 1;
```

This is because the buffer we add (1) is less than the hash block size (64) AND we can guarantee it is the first update called after initialization. IOW, ctx.len is guaranteed to be zero.

We also do not need to have a large temporary buffer _w[64] and padding[64], so we have more registers left on the GPU.

Here exemplary for kernel 14541, but this optimization should to be added to all kernels:

```
root@ht:~/hashcat# diff OpenCL/m14541_a3-pure.cl m14541_a3-pure.cl 
77,80d76
<   u32 padding[64] = { 0 };
< 
<   padding[0] = 0x00000041;
< 
104,109d99
<     u32x _w[64];
< 
<     u32 _w_len = pw_len;
< 
<     for (u32 i = 0; i < 64; i++) _w[i] = w[i];
< 
133c123,125
<       ripemd160_update (&ctx, padding, 1);
---
>       ctx.w0[0] = 0x00000041;
> 
>       ctx.len = 1;
135c127
<       ripemd160_update (&ctx, _w, _w_len);
---
>       ripemd160_update (&ctx0, w, pw_len);
273,276d264
<   u32 padding[64] = { 0 };
< 
<   padding[0] = 0x00000041;
< 
300,305d287
<     u32x _w[64];
< 
<     u32 _w_len = pw_len;
< 
<     for (u32 i = 0; i < 64; i++) _w[i] = w[i];
< 
329c311,313
<       ripemd160_update (&ctx, padding, 1);
---
>       ctx.w0[0] = 0x00000041;
> 
>       ctx.len = 1;
331c315
<       ripemd160_update (&ctx, _w, _w_len);
---
>       ripemd160_update (&ctx, w, pw_len);
```


The original speed on my GTX980 was:

```
Speed.#1.........:   104.9 MH/s 
```

And is now:

```
Speed.#1.........:   278.5 MH/s
```

I think it would makes sense to do this change.

**Comment by matrix** [comment]
Welcome back bro :) I'll make the changes as soon as possible.
For the extraction tool I waited for your comment, but as you have seen it is very simple.
Thanks

**Comment by matrix** [comment]
Hi, I should be done :)

```
$ for a in $(echo "14511 14512 14513 14521 14522 14523 14531 14532 14533 14541 14542 14543 14551 14552 14553"); do tools/test.sh -t all -m ${a} -a all -D1; done
[ test_1620432958 ] > Init test for hash type 14511.
[ test_1620432958 ] [ Type 14511, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 128 ] > OK : 0/1 not found
[ test_1620432958 ] [ Type 14511, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 192 ] > OK : 0/1 not found
[ test_1620432958 ] [ Type 14511, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 256 ] > OK : 0/1 not found
[ test_1620432958 ] [ Type 14511, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 128 ] > OK : 0/1 not found
[ test_1620432958 ] [ Type 14511, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 192 ] > OK : 0/1 not found
[ test_1620432958 ] [ Type 14511, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433001 ] > Init test for hash type 14512.
[ test_1620433001 ] [ Type 14512, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433001 ] [ Type 14512, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433001 ] [ Type 14512, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433001 ] [ Type 14512, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433001 ] [ Type 14512, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433001 ] [ Type 14512, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433045 ] > Init test for hash type 14513.
[ test_1620433045 ] [ Type 14513, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433045 ] [ Type 14513, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433045 ] [ Type 14513, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433045 ] [ Type 14513, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433045 ] [ Type 14513, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433045 ] [ Type 14513, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433088 ] > Init test for hash type 14521.
[ test_1620433088 ] [ Type 14521, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433088 ] [ Type 14521, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433088 ] [ Type 14521, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433088 ] [ Type 14521, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433088 ] [ Type 14521, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433088 ] [ Type 14521, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433131 ] > Init test for hash type 14522.
[ test_1620433131 ] [ Type 14522, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433131 ] [ Type 14522, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433131 ] [ Type 14522, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433131 ] [ Type 14522, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433131 ] [ Type 14522, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433131 ] [ Type 14522, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433175 ] > Init test for hash type 14523.
[ test_1620433175 ] [ Type 14523, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433175 ] [ Type 14523, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433175 ] [ Type 14523, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433175 ] [ Type 14523, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433175 ] [ Type 14523, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433175 ] [ Type 14523, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433221 ] > Init test for hash type 14531.
[ test_1620433221 ] [ Type 14531, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433221 ] [ Type 14531, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433221 ] [ Type 14531, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433221 ] [ Type 14531, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433221 ] [ Type 14531, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433221 ] [ Type 14531, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433270 ] > Init test for hash type 14532.
[ test_1620433270 ] [ Type 14532, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433270 ] [ Type 14532, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433270 ] [ Type 14532, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433270 ] [ Type 14532, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433270 ] [ Type 14532, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433270 ] [ Type 14532, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433320 ] > Init test for hash type 14533.
[ test_1620433320 ] [ Type 14533, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433320 ] [ Type 14533, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433320 ] [ Type 14533, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433320 ] [ Type 14533, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433320 ] [ Type 14533, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433320 ] [ Type 14533, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433372 ] > Init test for hash type 14541.
[ test_1620433372 ] [ Type 14541, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433372 ] [ Type 14541, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433372 ] [ Type 14541, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433372 ] [ Type 14541, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433372 ] [ Type 14541, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433372 ] [ Type 14541, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433420 ] > Init test for hash type 14542.
[ test_1620433420 ] [ Type 14542, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433420 ] [ Type 14542, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433420 ] [ Type 14542, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433420 ] [ Type 14542, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433420 ] [ Type 14542, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433420 ] [ Type 14542, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433463 ] > Init test for hash type 14543.
[ test_1620433463 ] [ Type 14543, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433463 ] [ Type 14543, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433463 ] [ Type 14543, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433463 ] [ Type 14543, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433463 ] [ Type 14543, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433463 ] [ Type 14543, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433508 ] > Init test for hash type 14551.
[ test_1620433508 ] [ Type 14551, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433508 ] [ Type 14551, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433508 ] [ Type 14551, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433508 ] [ Type 14551, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433508 ] [ Type 14551, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433508 ] [ Type 14551, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433554 ] > Init test for hash type 14552.
[ test_1620433554 ] [ Type 14552, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433554 ] [ Type 14552, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433554 ] [ Type 14552, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433554 ] [ Type 14552, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433554 ] [ Type 14552, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433554 ] [ Type 14552, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433602 ] > Init test for hash type 14553.
[ test_1620433602 ] [ Type 14553, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433602 ] [ Type 14553, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433602 ] [ Type 14553, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1, Key-Size 256 ] > OK : 0/1 not found
[ test_1620433602 ] [ Type 14553, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 128 ] > OK : 0/1 not found
[ test_1620433602 ] [ Type 14553, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 192 ] > OK : 0/1 not found
[ test_1620433602 ] [ Type 14553, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4, Key-Size 256 ] > OK : 0/1 not found

```

**Comment by matrix** [comment]
Hi @jsteube, missing something to do here?
Thanks

**Comment by jsteube** [comment]
Yes, the optimization that boost the speed * 2 for instance. Also the refactorization to the dynamic PT value.

**Comment by matrix** [comment]
> Yes, the optimization that boost the speed * 2 for instance. Also the refactorization to the dynamic PT value.

i think i've done it already, are you sure it's missing?

**Comment by jsteube** [comment]
Yes, I just checked. It's missing for sure. 

In all the kernels is like this:

```
u32 CT[4] = { 0 };
```

**Comment by jsteube** [comment]
OK, I see everything was updated accordingly. Great PR man!

**Pull request merged**
