### PR TITLE
Add custom tuning settings for Iris Pro / SHA-3(Keccak)

### PR DESCRIPTION
**Pull request by matrix**
#412

### CODE REVIEW

**Comment by leonklingele** [comment]
This fixes #412, yay!

**Comment by matrix** [comment]
@leonklingele, could you do a full benchmark only with Iris Pro device to identify eventually other problems?
Thanks

**Comment by leonklingele** [comment]
@matrix I can't :/ It still crashes when benchmarking Whirlpool: https://github.com/hashcat/hashcat/issues/412#issuecomment-264703313

**Comment by jsteube** [comment]
Just a suggestion, why don't you just pair the Iris and Iris Pro into a group so that the tuning will work on both the same way? hashcat.hctune supports that.

**Comment by matrix** [comment]
@jsteube I will see why Apple named it as "Pro" before set an alias in hctune :)

**Pull request merged**
