### PR TITLE
CRAM_MD5 throws salt length exception when the issue is in the hash

### PR DESCRIPTION
**Pull request by ghost**
Maybe an oversight when porting or am I missing a reason why the hash_len has anything to do with the salt?

### CODE REVIEW

**Comment by ghost** [comment]
Added additional output per #449.  The output probably needs work but does compile cleanly and did display properly in my tests.

-a 3

> Session.Name...: hashcat
> Status.........: Aborted
> Input.Mode.....: Mask (?1?1?1?1?1?1?1?1) [8]
> Custom.Chars...: -1 ?l?u, -2 ?s?d, -3 (null), -4 (null)
> Hash.Target....: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
> Hash.Type......: MD5

-a 6

> Session.Name...: hashcat
> Status.........: Aborted
> Input.Left.....: File (../dicts/dict)
> Input.Right....: Mask (?1?2) [2]
> Custom.Chars...: -1 ?l?u, -2 ?s?d, -3 (null), -4 (null)
> Hash.Target....: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
> Hash.Type......: MD5

-a 7

> Session.Name...: hashcat
> Status.........: Aborted
> Input.Left.....: Mask (?1?2) [2]
> Input.Right....: File (../dicts/dict)
> Custom.Chars...: -1 ?l?u, -2 ?s?d, -3 (null), -4 (null)
> Hash.Target....: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
> Hash.Type......: MD5

**Comment by jsteube** [comment]
OK so far, but please add a description to docs/changes

**Comment by ghost** [comment]
Done.

**Comment by jsteube** [comment]
You can't have (null) output otherwise this crashes on Windows. Please check for NULL and handle it correctly.

**Comment by ghost** [comment]
Done.

**Comment by jsteube** [comment]
Thanks!

**Pull request merged**
