### PR TITLE
Fix base58 charset check

### PR DESCRIPTION
**Pull request by PenguinKeeper7**
See https://github.com/hashcat/hashcat/issues/3878

### CODE REVIEW

**Review by magnumripper — COMMENTED** [review]
Assuming this function is performance critical, you might want to replace all those lockstep conditionals (the old and the new) with a single lookup in a static 128-byte table.

**Comment by PenguinKeeper7** [comment]
> Assuming this function is performance critical, you might want to replace all those lockstep conditionals (the old and the new) with a single lookup in a static 128-byte table.

I tested performance for this commit, it seemed identical to pre-commit. The tiny single u8 comparison is nothing in comparison to the computation of AES/SHA256 that the few kernels that use this check also have to perform. Seems like overcomplication but I can test if you feel it'd affect performance above margin of error?

**Comment by GuzziRaz** [comment]
> I tested performance for this commit, it seemed identical to pre-commit. The tiny single u8 comparison is nothing in comparison to the computation of AES/SHA256 that the few kernels that use this check also have to perform. Seems like overcomplication but I can test if you feel it'd affect performance above margin of error?

Nah probably not worth it then. Just saying it'd be easy and perhaps the function is used in other places?

Anyway good find on the initial bug - kinda hard to spot if you're not looking for it.

**Comment by magnumripper** [comment]
> I tested performance for this commit, it seemed identical to pre-commit. The tiny single u8 comparison is nothing in comparison to the computation of AES/SHA256 that the few kernels that use this check also have to perform. Seems like overcomplication but I can test if you feel it'd affect performance above margin of error?

Nah probably not worth it then. Just saying it'd be easy and perhaps the function is used in other places?

Anyway good find on the initial bug - kinda hard to spot if you're not looking for it.

**Pull request merged**
