### PR TITLE
Add hash modes 19800 (krb5pa etype 17) and 19900 (krb5pa etype 18)

### PR DESCRIPTION
**Pull request by brandoncasaba**
I've ported the TGS code from @Fist0urs with pull https://github.com/hashcat/hashcat/pull/1955 to work with KRB5PA. I simplified a lot of the decryption code for the encrypted pre-auth blobs since they are of known lengths. This also allowed some minor optimizations which only minimally improved performance. The majority of the workings are the same, but the cryptography constants for the pre-auth token are different and the locations of any successful decryption canaries are different. 

This will properly close my issue I've been wishing for for years #959. Cracking PA and TGS tickets is extraordinarily useful for gaining a foothold in environments with minimal NTLMv2 traffic where you have network access and do not yet have a domain credential and end users with poor passwords are using the network. 

Performance is very similar to that of the TGS code, using a single 1060 6GB on my test machine:

```
Hashmode: 19600 - Kerberos 5 TGS-REP etype 17 (AES128-CTS-HMAC-SHA1-96) (Iterations: 4095)

Speed.#1.........:   409.2 kH/s (48.93ms) @ Accel:1024 Loops:256 Thr:32 Vec:1

Hashmode: 19700 - Kerberos 5 TGS-REP etype 18 (AES256-CTS-HMAC-SHA1-96) (Iterations: 4095)

Speed.#1.........:   201.8 kH/s (49.81ms) @ Accel:512 Loops:256 Thr:32 Vec:1

Hashmode: 19800 - Kerberos 5 Pre-Auth etype 17 (AES256-CTS-HMAC-SHA1-96) (Iterations: 4095)

Speed.#1.........:   409.1 kH/s (49.01ms) @ Accel:1024 Loops:256 Thr:32 Vec:1

Hashmode: 19900 - Kerberos 5 Pre-Auth etype 18 (AES256-CTS-HMAC-SHA1-96) (Iterations: 4095)

Speed.#1.........:   202.4 kH/s (49.60ms) @ Accel:512 Loops:256 Thr:32 Vec:1

```

Here are a few captured hashes directly from my test lab, including a token which is a length of 55 instead of 56 bytes. Many of the implementations seem to fix on a size of 56 bytes, this one does not fwiw.

```
$krb5pa$18$labuser$CORP.LABDOMAIN.COM$83fe86b5d33168e5f5414387f0fe7f18066d50143d8011048a91b1ec99ded34279325ee4f0b40500af5b56c8fff2a571337ffaf3aefe69:LabPass!
$krb5pa$18$labuser$CORP.LABDOMAIN.COM$a800161c71035d4a8c84130fff4f3dcef29fc0cf128acd445c5c4a099583079d4a14714320807bca1a1247c94512160b7170569344e2815b:LabPass!
```
Also any of the samples from JtR will work: https://www.openwall.com/lists/john-users/2012/11/18/5/1

### CODE REVIEW

**Comment by philsmd** [comment]
we already have -m 19811, -m 19812 and -m 19813 for DiskCryptor and since @jsteube ask to use 199xx over here: https://github.com/hashcat/hashcat/pull/1939#issuecomment-480601504, we probably would need to use at least 20000 and 20100 for this new hash type (this PR).
Could you in the meantime update the hash type number, while devs are reviewing it.
Thank you very much for you work

**Comment by brandoncasaba** [comment]
I have never really understood the mode number scheme, would 19610 and 19710 or 19650 and 19750 make more sense since it's essentially a variation of 19600 and 19700?

**Comment by jsteube** [comment]
Thanks for your PR. Before we can merge, we need to fix some issues. Let's do it one step after another. The most important thing is to get the unit test working correctly in order to run the tests.

This is what I'm getting:

```
root@sf:~/hashcat# echo hashcat | tools/test.pl passthrough 19900
Use of uninitialized value $checksum in sprintf at /root/git/hashcat/tools/test_modules/m19900.pm line 167, <> line 1.
$krb5pa$18$user$realm$207167724fd4447f60d1c68fb2bed8dcf4f006743f3bcf6413615e38c01754331a60fcaa7fd8aece15edb0d1
```

Trying to load this will cause an error on hashcat:

```
Hash '$krb5pa$18$user$realm$207167724fd4447f60d1c68fb2bed8dcf4f006743f3bcf6413615e38c01754331a60fcaa7fd8aece15edb0d1': Token length exception
No hashes loaded.
```

**Comment by brandoncasaba** [comment]
Apologies, perl script should be fixed now.

**Comment by jsteube** [comment]
Great contribution, thanks!

**Pull request merged**
