### PR TITLE
Add casts where needed in C++ mode

### PR DESCRIPTION
**Pull request by neheb**
Otherwise, -fpermissive must be passed.

### CODE REVIEW

**Comment by matrix** [comment]
Hi @neheb 
why C++ ?

**Comment by neheb** [comment]
Treating the code as C++ helps with static analyzers to find more stuff.

As for these errors, C++ is more strict when it comes to void pointers, hence the need to cast.

**Comment by neheb** [comment]
On maskprocessor, simply by compiling as C++ I was able to get a speedup...

```
mangix@DESKTOP-VIRSTQA:~/devstuff/maskprocessor/src$ time ../mp64.bin ?a?a?a?a?a > /dev/null

real    0m49.891s
user    0m41.797s
sys     0m8.094s
mangix@DESKTOP-VIRSTQA:~/devstuff/maskprocessor/src$ time ../mp64.bin ?a?a?a?a?a > /dev/null

real    0m49.607s
user    0m42.188s
sys     0m7.406s
mangix@DESKTOP-VIRSTQA:~/devstuff/maskprocessor/src$ time ./mp64.bin ?a?a?a?a?a > /dev/null

real    0m51.531s
user    0m42.750s
sys     0m8.781s
mangix@DESKTOP-VIRSTQA:~/devstuff/maskprocessor/src$ time ./mp64.bin ?a?a?a?a?a > /dev/null

real    0m51.607s
user    0m43.156s
sys     0m8.453s
mangix@DESKTOP-VIRSTQA:~/devstuff/maskprocessor/src$
```

.. = g++, . = gcc .

The only change was: 

```
--- a/src/mp.cxx
+++ b/src/mp.cxx
@@ -805,7 +805,7 @@ int main (int argc, char *argv[])
     seq_start[len] = (off > 0) ? off : 0;
   }

-  out_t *out = malloc (sizeof (out_t));
+  out_t *out = (out_t *) malloc (sizeof (out_t));

   for (len = min; len <= max; len++)
   {
```

**Comment by matrix** [comment]
> On maskprocessor, simply by compiling as C++ I was able to get a speedup...
> 
> ```
> mangix@DESKTOP-VIRSTQA:~/devstuff/maskprocessor/src$ time ../mp64.bin ?a?a?a?a?a > /dev/null
> 
> real    0m49.891s
> user    0m41.797s
> sys     0m8.094s
> mangix@DESKTOP-VIRSTQA:~/devstuff/maskprocessor/src$ time ../mp64.bin ?a?a?a?a?a > /dev/null
> 
> real    0m49.607s
> user    0m42.188s
> sys     0m7.406s
> mangix@DESKTOP-VIRSTQA:~/devstuff/maskprocessor/src$ time ./mp64.bin ?a?a?a?a?a > /dev/null
> 
> real    0m51.531s
> user    0m42.750s
> sys     0m8.781s
> mangix@DESKTOP-VIRSTQA:~/devstuff/maskprocessor/src$ time ./mp64.bin ?a?a?a?a?a > /dev/null
> 
> real    0m51.607s
> user    0m43.156s
> sys     0m8.453s
> mangix@DESKTOP-VIRSTQA:~/devstuff/maskprocessor/src$
> ```
> 
> .. = g++, . = gcc .
> 
> The only change was:
> 
> ```
> --- a/src/mp.cxx
> +++ b/src/mp.cxx
> @@ -805,7 +805,7 @@ int main (int argc, char *argv[])
>      seq_start[len] = (off > 0) ? off : 0;
>    }
> 
> -  out_t *out = malloc (sizeof (out_t));
> +  out_t *out = (out_t *) malloc (sizeof (out_t));
> 
>    for (len = min; len <= max; len++)
>    {
> ```

I've already recompiled all hashcat in C ++ but I didn't get any performance gains. This is because I think it should be rewritten in C ++ and not just recompiled.

**Comment by jsteube** [comment]
I can't see any disadvantages caused by the changes. Therefore, I will merge it.

**Comment by neheb** [comment]
That performance discussion was due to GCC bugs. Speed goes to 45 seconds in both modes on GCC9.

**Pull request merged**
