### PR TITLE
Replace some snprintf calls with asprintf.

### PR DESCRIPTION
**Pull request by neheb**
Simplifies the code.

Runtime tested. Seems to work fine.

### CODE REVIEW

**Comment by jsteube** [comment]
Nice! Thanks

**Comment by jsteube** [comment]
I'm getting tons of those now:

warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]

**Comment by neheb** [comment]
Is this on OS X?

**Comment by jsteube** [comment]
No, Ubuntu 16.04

**Comment by neheb** [comment]
agh this also seems to be a problem in 14.04. And only in Ubuntu.

So far I have been unable to reproduce in Fedora, MinGW, or Cygwin. This sounds like Ubuntu's version of glibc has a very specific patch to add warn_unused_result to asprintf. Hillarious since neither malloc nor snprintf do.

I'd suggest adding -Wno-unused-result in the Makefile to silence the warning.

**Comment by jsteube** [comment]
Added a wrapping function: https://github.com/hashcat/hashcat/commit/6ece83760d3501ee34a8ee2076751edb8945dd81

**Pull request merged**
