### PR TITLE
Adding PostgreSQL SCRAM-SHA-256 hash mode - #3038

### PR DESCRIPTION
**Pull request by b0lek**
PostgreSQL SCRAM-SHA-256 is based on mode 24200 for MongoDB. Solves #3038.

Adding new module as it makes sense to have a module parsing exact data from the database and in both cases algorithm is the same but stored data are in different format and stores different data:
`SCRAM-SHA-256$4096:IKfxzJ8Nq4PkLJCfgKcPmA==$iRw3qwTp18uaBnsTOEExbtgWdKeBMbSSnZvqD4sdqLQ=:hPciC1CcnBna3szR8Mf3MVc8t0W7QPbIHoMMrh4zRV0=`
vs
`$mongodb-scram$*1*dXNlcg==*15000*qYaA1K1ZZSSpWfY+yqShlcTn0XVcrNipxiYCLQ==*QWVry9aTS/JW+y5CWCBr8lcEH9Kr/D4je60ncooPer8=`

Main difference is in `/src/modules/module_94200.c`. Minor adjustments in `/OpenCL/m94200-pure.cl`.

Tests added as well.

### CODE REVIEW

**Comment by philsmd** [comment]
Is this hash format `SCRAM-SHA-256$...` the same format that john supports, i.e. same fields etc ?

Why you choose such a high hash type number (-m 94200) ? It's best to use a only slightly (maybe +200 or +300) more than the latest hash type we've added.

**Comment by clem9669** [comment]
John did not recognized either
```sh
 user@kali  ~  xclip -o > a              
 user@kali  ~  john a     
Using default input encoding: UTF-8
No password hashes loaded (see FAQ)
 user@kali  ~  cat a            
SCRAM-SHA-256$4096:IKfxzJ8Nq4PkLJCfgKcPmA==$iRw3qwTp18uaBnsTOEExbtgWdKeBMbSSnZvqD4sdqLQ=:hPciC1CcnBna3szR8Mf3MVc8t0W7QPbIHoMMrh4zRV0=%                                                                                                        
user@kali  ~  xclip -o > b
 user@kali  ~  john b
Using default input encoding: UTF-8
No password hashes loaded (see FAQ)
 user@kali  ~  cat b                 
$mongodb-scram$*1*dXNlcg==*15000*qYaA1K1ZZSSpWfY+yqShlcTn0XVcrNipxiYCLQ==*QWVry9aTS/JW+y5CWCBr8lcEH9Kr/D4je60ncooPer8=% 
```

john seems to support scram but not 100% clear to me
```sh
 user@kali  ~  john --list=formats | grep scram
MD2, mdc2, MediaWiki, monero, money, MongoDB, scram, Mozilla, mscash, 
 user@kali  ~  john --list=format-details | grep scram
scram	125	32	2048	01000003	2	SCRAM PBKDF2-SHA1 256/256 AVX2 8x			0x107	20	156		0	$scram$someadmin$10000$wf42AF7JaU1NSeBaSmkKzw==$H6A5RF0qz6DrcWNNX4xe+wIeVEw=

```

**Comment by b0lek** [comment]
> Is this hash format `SCRAM-SHA-256$...` the same format that john supports, i.e. same fields etc ?

I tried to find what format john is using but I've failed. Even if the algorithm is the same it has parameters and each user can store keys in a different format. Diff between MongoDB and PostgreSQL is quite significant. So I still believe it is good to accept exact format from database and have a mode that is dedicated for PostgreSQL.




> Why you choose such a high hash type number (-m 94200) ? It's best to use a only slightly (maybe +200 or +300) more than the latest hash type we've added.

I've fixed mod number to 28600 to have 28500 for the other one in the backlog.

Thanks.

**Comment by jsteube** [comment]
Great PR, many thanks! All test.sh tests succeeded on my systems.

**Comment by Neustradamus** [comment]
Thanks @b0lek for the PR and @jsteube for merging! :)

Thanks @clem9669, @philsmd, @matrix too.

Linked to:
- https://github.com/scram-sasl/info/issues/1

**Pull request merged**
