### PR TITLE
New appveyor

### PR DESCRIPTION
**Pull request by stephengroat**
also cleanup travis and `git submodule` command

### CODE REVIEW

**Comment by stephengroat** [comment]
#1032

**Comment by philsmd** [comment]
I played around with appveyor too, with this .appveyor.yml file:
```
environment:
  CYG_MIRROR: http://cygwin.mirror.constant.com
  CYG_PACKAGES: make,gcc-core,clang
  matrix:
    - MSYSTEM: MINGW64
      BASH: C:\msys64\usr\bin\bash
      MSYS_CACHE: C:\msys64\var\cache\pacman\pkg
      CC: gcc
    - MSYSTEM: MINGW32
      BASH: C:\msys64\usr\bin\bash
      MSYS_CACHE: C:\msys64\var\cache\pacman\pkg
      CC: gcc
    - CYG_ROOT: C:\cygwin64
      CYG_CACHE: C:\cygwin64\var\cache\setup
      CYG_SETUP: setup-x86_64.exe
      BASH: C:\cygwin64\bin\bash
      CC: gcc
    - CYG_ROOT: C:\cygwin
      CYG_CACHE: C:\cygwin\var\cache\setup
      CYG_SETUP: setup-x86.exe
      BASH: C:\cygwin\bin\bash
      CC: gcc
    - MSYSTEM: MINGW64
      BASH: C:\msys64\usr\bin\bash
      MSYS_CACHE: C:\msys64\var\cache\pacman\pkg
      CC: clang
    - MSYSTEM: MINGW32
      BASH: C:\msys64\usr\bin\bash
      MSYS_CACHE: C:\msys64\var\cache\pacman\pkg
      CC: clang
    - CYG_ROOT: C:\cygwin64
      CYG_CACHE: C:\cygwin64\var\cache\setup
      CYG_SETUP: setup-x86_64.exe
      BASH: C:\cygwin64\bin\bash
      CC: clang
    - CYG_ROOT: C:\cygwin
      CYG_CACHE: C:\cygwin\var\cache\setup
      CYG_SETUP: setup-x86.exe
      BASH: C:\cygwin\bin\bash
      CC: clang

clone_depth: 1

init:
  # Don't try to convert line endings to Win32 CRLF
  - git config --global core.autocrlf input

install:
  - ps: if (Test-Path Env:\CYG_ROOT) { Start-FileDownload "http://cygwin.com/$env:CYG_SETUP" -FileName "$env:CYG_SETUP" }
  - if defined CYG_ROOT (%CYG_SETUP% --quiet-mode --no-shortcuts --only-site --root "%CYG_ROOT%" --site "%CYG_MIRROR%" --local-package-dir "%CYG_CACHE%" --packages "%CYG_PACKAGES%" --upgrade-also)
  - if defined MSYSTEM (%BASH% -lc "pacman -Suuy --noconfirm")

build_script:
  - if defined BASH (%BASH% -lc "cd $(cygpath ${APPVEYOR_BUILD_FOLDER}) && git submodule init && git submodule update && make")

test_script:
  # some file globbing tests
  #  1. hash file should not exist and therefore hashcat should complain (if it does not there might be a problem)
  #  2. hash file should expand to example0.hash and succeed
  - ps: >-
      .\hashcat -m 0 --show *file_not_found.hash 2>&1 | out-null

      if ($LastExitCode -eq 0)
      {
        throw "test failed"
      }

      .\hashcat -m 0 --show *ple0.hash
```
Note: you have a duplicate line (- if defined MSYSTEM (%BASH% -lc "pacman -Suuy --noconfirm"))

the problem is, the globbing still fails on cygwin, see https://ci.appveyor.com/project/philsmd/hashcat/build/1.0.38/job/vcqi2ole1nxvc1k2#L330

Can you merge our files please @stephengroat ?

**Comment by stephengroat** [comment]
the dupe command is necessary to upgrade the MSYS base files and then all the packages. and 2 separate lines are needed because a new shell is necessary for each step

i'll check on the other issue tonight when i can rdp into the system

update:
@philsmd the specific error that I'm getting from `hashcat -m 0 --show *ple0.hash` is 
screenshot 2017-02-09 at 20 14 57
I think that's an issue with that dll not being in the system path, right?

**Comment by neheb** [comment]
@philsmd Cygwin binaries are not meant to be ran from the windows command line. That's what MinGW is for. Pretty sure the tests pass under mintty (or w/e the default shell is called).

**Comment by jsteube** [comment]
I'll merge this now, because I'd like to see the compile process getting tested. If the tests in the post compilation process fail that's bad and you should remove or fix by creating a new PR. One step at a time!

**Pull request merged**
