### PR TITLE
LUKS strings

### PR DESCRIPTION
**Pull request by ventaquil**
Similar changes like in GH-3293 and GH-3302 but for LUKS modules.

TODO:

- [x] ~~Add tests for new modules.~~
- [ ] Add missing Whirlpool kernels.

```
- [ Hash modes ] -

      # | Name                                                       | Category
  ======+============================================================+======================================
  14600 | LUKS v1 (legacy)                                           | Full-Disk Encryption (FDE)
  29541 | LUKS v1 RIPEMD-160 + AES                                   | Full-Disk Encryption (FDE)
  29542 | LUKS v1 RIPEMD-160 + Serpent                               | Full-Disk Encryption (FDE)
  29543 | LUKS v1 RIPEMD-160 + Twofish                               | Full-Disk Encryption (FDE)
  29511 | LUKS v1 SHA-1 + AES                                        | Full-Disk Encryption (FDE)
  29512 | LUKS v1 SHA-1 + Serpent                                    | Full-Disk Encryption (FDE)
  29513 | LUKS v1 SHA-1 + Twofish                                    | Full-Disk Encryption (FDE)
  29521 | LUKS v1 SHA-256 + AES                                      | Full-Disk Encryption (FDE)
  29522 | LUKS v1 SHA-256 + Serpent                                  | Full-Disk Encryption (FDE)
  29523 | LUKS v1 SHA-256 + Twofish                                  | Full-Disk Encryption (FDE)
  29531 | LUKS v1 SHA-512 + AES                                      | Full-Disk Encryption (FDE)
  29532 | LUKS v1 SHA-512 + Serpent                                  | Full-Disk Encryption (FDE)
  29533 | LUKS v1 SHA-512 + Twofish                                  | Full-Disk Encryption (FDE)
```

### CODE REVIEW

**Comment by ventaquil** [comment]
Another proposition - generated strings are very huge, I am planning to change the way how they are shown when hit occurs (replace central part with dots).

**Comment by ventaquil** [comment]
I have checked header in version 2 and I can update `luks2hashcat.py` script to extract data from newer containers, however I am not quite sure what to do with Argon2... I will try to find some implementations for GPUs.

**Comment by ventaquil** [comment]
Another proposition - I will leave this PR to create new LUKS modules for header in version 1 (maybe only with adding missing Whirlpool kernels).

I will create new PR (when I will have some free time) with modules for header in version 2 (with or without Argon2 support).

What do you think guys?

**Comment by ventaquil** [comment]
Argon2 support requested here: GH-1966.

LUKS v2 support requested here: GH-2178.

**Comment by jsteube** [comment]
Right now there's no Argon 2 implementation in hashcat. But that shouldn't be relevant for this particular PR. We can also, if needed, make a new mode for LUKS2. Is this one ready for merge?

**Comment by ventaquil** [comment]
Yep, it's ready to merge right now (I added tests).

I removed support for Whirlpool function (modules `29551`-`29553`). it's not so easy for me to add it so I will make new PR when it will be done.

I can also prepare support for v2 (currently only for PBKDF2 mode since Hashcat doesn't have Argon2 support).

**Comment by jsteube** [comment]
Fantastic, thanks!

**Comment by philsmd** [comment]
hey @ventaquil 

I think this commit introduced some new warnings, see: https://ci.appveyor.com/project/jsteube/hashcat/builds/43985647/job/v7i09blxaj659336#L1501

could you please investigate them ?

**Comment by ventaquil** [comment]
Hey @philsmd, I will look into it!

**Comment by ventaquil** [comment]
Unfortunately when I am compiling it locally I got no errors/warnings.

```
$ make modules/module_29511.so
gcc    -std=gnu99 -W -Wall -Wextra -O2 -pipe -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib -Ideps/zlib/contrib -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash -DWITH_CUBIN -Ideps/unrar -DWITH_HWMON src/modules/module_29511.c obj/combined.NATIVE.a -o modules/module_29511.so  -s -lstdc++ -lpthread -ldl -lrt -lm -shared -fPIC -D MODULE_INTERFACE_VERSION_CURRENT=630
```

Theoretically `cipher_mode` can be left uninitialized here however I am using all possible values from `hc_luks_cipher_mode_t`.

https://github.com/hashcat/hashcat/blob/e0fae5c7ab0e94dd8c536c0909fef429f2628f5b/src/modules/module_29511.c#L341-L350

What should I do in `default:` case? Return `0` or `-1`? As far as I checked I didn't have seen any checks in case of encoding errors.

**Comment by philsmd** [comment]
maybe to be extra safe, you could just initialize the variable (when it is declared, like `u32 key_size = HC_LUKS_KEY_SIZE_128;`) and in addition to that either directly return an error within the `switch` statement or set a invalid value and catch / check it after the switch statement (that is how I would do it, just be extra safe, even though most other/newer compilers seem to understand that it's kind of impossible to even enter a branch that is **none** of the excepted one, because already checked beforehand).

Thx

**Comment by philsmd** [comment]
it seems my reported problem was fixed with 9fe51563b1b08279e0acb5e23b4f66d49b24e749
Thanks

**Pull request merged**
