### PR TITLE
Longer passwords

### PR DESCRIPTION
**Pull request by deepubhullar**
merge with master

### CODE REVIEW

**Comment by jsteube** [comment]
Sorry, I don't want to merge this experimental code with master yet

**Comment by deepubhullar** [comment]
where i can download compiled long password branch for windows operating
system?

**Comment by jsteube** [comment]
There's​ no such Thing

Am 27.05.2017 06:21 schrieb "deepubhullar" <notifications@github.com>:

**Comment by deepubhullar** [comment]
please compile long password branch for windows for me.
Thank You.

**Comment by deepubhullar** [comment]
i know you created file inc_hash_sha512.cl for long password please provide me that for long passwords.
thank you.

**Pull request closed without merging**
