### PR TITLE
Dependencies: Updated LZMA SDK to 22.01

### PR DESCRIPTION
**Pull request by matrix**

### CODE REVIEW

**Comment by jsteube** [comment]
I think some small modifications are required. Try to compile with  "make binaries" to reproduce:

```
root@ht:~/hashcat# make -s binaries
deps/LZMA-SDK/C/Alloc.c:9:10: fatal error: Windows.h: No such file or directory
    9 | #include <Windows.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [src/Makefile:803: obj/Alloc.LZMA.WIN.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by matrix** [comment]
> I think some small modifications are required. Try to compile with "make binaries" to reproduce:
> 
> ```
> root@ht:~/hashcat# make -s binaries
> deps/LZMA-SDK/C/Alloc.c:9:10: fatal error: Windows.h: No such file or directory
>     9 | #include <Windows.h>
>       |          ^~~~~~~~~~~
> compilation terminated.
> make: *** [src/Makefile:803: obj/Alloc.LZMA.WIN.o] Error 1
> make: *** Waiting for unfinished jobs....
> ```

yep, now will works

Thanks! ;)

**Comment by jsteube** [comment]
Now all lines are being updated. CRLF Problem?

**Comment by matrix** [comment]
Yes, but the real patch is [fix LZMA_SDK Windows.h includes](https://github.com/hashcat/hashcat/pull/3721/commits/ecc03008a02686783f0404e5d44e3bd45693fbdc)

**Comment by jsteube** [comment]
I understand, but the CRLF it's 1:1 like original or changed by you?

**Comment by matrix** [comment]
The original code is with CRLF, but it's not visible from github

**Comment by matrix** [comment]
from master:

```
$ file deps/LZMA-SDK/C/7z.h 
deps/LZMA-SDK/C/7z.h: c program text, ASCII text, with CRLF line terminators
```

**Pull request merged**
