### PR TITLE
restyling hwmon

### PR DESCRIPTION
**Pull request by matrix**
- moved functions from hwmon.c to .c/.h
- code style

### CODE REVIEW

**Comment by jsteube** [comment]
I did not go into detail yet, but this breaks use on my Linux Box. 

Before:

```
Hardware.Mon.#1..: Temp: 81c Fan: 45% Util: 96% Core:1126MHz Mem:3004MHz Bus:16
```

After:

```
Hardware.Mon.#1..: N/A
```

**Comment by matrix** [comment]
I will do a recheck as soon as possible. Thanks

**Comment by matrix** [comment]
Fixed, now works

**Comment by jsteube** [comment]
Yeah, it works on Linux now. It also works with MinGW but on cygwin, I'm getting a segfault. Without this patch, it works fine.

**Comment by matrix** [comment]
probably I miss something from the original patch ...
as soon as I understand the problem I will update the PR.
Thanks

**Comment by matrix** [comment]
I can't reproduce it because the monitor hardware is not activated inside the VM ... @philsmd have you a windows machine native with hashcat to check what is wrong with cygwin here ?
Thanks!

**Comment by jsteube** [comment]
Can you fix the conflict so that we can continue to work on this?

**Comment by jsteube** [comment]
@matrix Please update status on this PR

**Comment by matrix** [comment]
check here #2806

**Pull request closed without merging**
