### PR TITLE
Add module and unit test for -m 18000 (& -m 17600 module)

### PR DESCRIPTION
**Pull request by mhasbini**
Updated configurations as well:

Updated `salt_type` from `SALT_TYPE_EMBEDDED` to `SALT_TYPE_NONE`.
Added `OPTS_TYPE_STATE_BUFFER_LE` to `OPTS_TYPE`.

### CODE REVIEW

**Comment by jsteube** [comment]
Not sure why there's a conflict. I just merged the PR in the correct order.

**Comment by jsteube** [comment]
Please fix the conflict first or close this PR and open a new one?

**Comment by jsteube** [comment]
Nevermind I fixed the conflicts inline.

Thanks for PR!

**Comment by mhasbini** [comment]
👍

**Pull request merged**
