### PR TITLE
Added -m 29500 (Flask session cookie)

### PR DESCRIPTION
**Pull request by TomStokes14**
Morning folks!

This PR is for the flask session cookie as mentioned in issue #3239 . Functionally it's hmac-sha1($pass.$fixed-salt) --> hmac-sha1($result-of-previous.$salt)

The salt is 1 iteration, literally having to do nothing with it really. I've not written a flat kernel and my testing has passed on the 3 separate CL files. I've never written in Perl before but if its something thats required on my end just let me know and I'll see what I can do!

### CODE REVIEW

**Comment by jsteube** [comment]
Hey there, many thanks for the contribution. No worries, I'll add the unit test test (perl) later.

**Comment by TomStokes14** [comment]
many thanks @jsteube, working on optimising some things inside the kernel - am I right in saying that the point where I start assuming password lengths !>64, then I am to write that in an optimized kernel, and that the pure kernels must **always** support longer lengths of plains?

**Comment by jsteube** [comment]
So far there's only pure kernels and they should support up to length 256. As far as I can see your kernels follow the regular template kernels so they should in theory support already passwords up to length 256.

Here's the unit test: https://github.com/hashcat/hashcat/commit/ed3b5218559710e96595c43fe79b9e8d36cb794a

And the results:

```
$ tools/test.sh -t all -a all -m 29500 -V1
[ test_1652883963 ] > Init test for hash type 29500.
[ test_1652883963 ] [ Type 29500, Attack 0, Mode single, Device-Type Gpu, Kernel-Type Optimized, Vector-Width 1 ] > OK : 0/8 not found, 0/8 not matched, 0/8 timeout, 0/8 skipped
[ test_1652883963 ] [ Type 29500, Attack 0, Mode multi,  Device-Type Gpu, Kernel-Type Optimized, Vector-Width 1 ] > OK : 0/1 not found, 0/1 not matched, 0/1 timeout, 0/1 skipped
[ test_1652883963 ] [ Type 29500, Attack 1, Mode single, Device-Type Gpu, Kernel-Type Optimized, Vector-Width 1 ] > OK : 0/7 not found, 0/7 not matched, 0/7 timeout, 0/7 skipped
[ test_1652883963 ] [ Type 29500, Attack 1, Mode multi,  Device-Type Gpu, Kernel-Type Optimized, Vector-Width 1 ] > Error : 1/1 not found, 0/1 not matched, 0/1 timeout, 0/1 skipped
[ test_1652883963 ] [ Type 29500, Attack 3, Mode single, Device-Type Gpu, Kernel-Type Optimized, Vector-Width 1 ] > OK : 0/7 not found, 0/7 not matched, 0/7 timeout, 0/7 skipped
[ test_1652883963 ] [ Type 29500, Attack 3, Mode multi,  Device-Type Gpu, Kernel-Type Optimized, Vector-Width 1 ] > OK : 0/1 not found, 0/1 not matched, 0/1 timeout, 0/1 skipped
```

I've not checked what's the reason for failing in -a 1 mode so far.

Another odd thing to  me is that the module parser restricted the message length to a pretty short length. 

```
  token.sep[0]     = '.';
  token.len_min[0] = 0; 
  token.len_max[0] = 27;
  token.attr[0]    = TOKEN_ATTR_VERIFY_LENGTH
                   | TOKEN_ATTR_VERIFY_BASE64C;
```

If you decode the message you can see it's just an array that assigns a username. But usernames can have arbitrary lengths, so we should allow more data here. The salt_t structure supports up to 256 bytes (that is including the timestamp and in base64 encoding). 

For now I've just fixed the unit test to make sure to stay below data length 27 by using this:

```
  my $username = random_number (10000, 99999);
```

**Comment by TomStokes14** [comment]
right, my apologies it seems my first module is most certainly not flawless! I'll take a look at whats going awry with the multiple's hopefully today if not tomorrow. Many thanks for throwing that perl module together! I'll take a look at token[0] after I've got those fixed :)

**Comment by jsteube** [comment]
Here's the fix: https://github.com/hashcat/hashcat/commit/446d82d8ea5442569a76b845977fb2227a908b9c

```
    sha1_hmac_init_swap (&ctx, c, pw_len + comb_len);
    sha1_hmac_init (&ctx, c, pw_len + comb_len);
```

Also this one seems odd:

```
    sha1_hmac_init (&ctx, intermediate, 16);
```

I think it should be 20 not 16, but because how the HMAC function works (and how we have it optimized) it still works. Anyway I think it should be updated in all kernels just to have it easier to read. Feel free to send in another PR.

**Comment by jsteube** [comment]
Changes:
https://github.com/hashcat/hashcat/commit/2e8ba6ba2ca5d9638d9cb00e72f57e19ed4e3c17
https://github.com/hashcat/hashcat/commit/5581665977a55098a84be1f4e3d385a556f6feb5

One improves the cracking performance, the other one just renames -m 29500 to 29100.

**Pull request merged**
