### PR TITLE
Filter out OpenCL Intel Runtime broken check on Apple

### PR DESCRIPTION
**Pull request by matrix**

### CODE REVIEW

**Comment by jsteube** [comment]
Can you please rewrite so that it does not use a NOT. We try to stick to positive cases only for easier reading.

**Comment by matrix** [comment]
Ok, is broken only in windows?

**Comment by jsteube** [comment]
All systems (just not apple?)

**Comment by matrix** [comment]
If only Apple is not affected the right code has already been written :)

**Pull request merged**
