### PR TITLE
Added blake2b pure kernel.

### PR DESCRIPTION
**Pull request by DoZ10**
As requested by https://github.com/hashcat/hashcat/issues/1298

### CODE REVIEW

**Comment by jsteube** [comment]
Thanks for the PR. Unfortionally is not working:

```
$ cat > word
818056996477908596053867963937153122281569556196626724373208444049017873518590378196026328873050351418134563015288406069916717700093738476830903740241096203797808820424262302083527675902345553260107437135663063783949390635
$ cat > hash
$BLAKE2$a704958aa4ba43c541a0589399f4cbac9718d1180ce6d851c66286cc668a1d8ddcce8ab888f4572f99e17f34979b118fc485c6bd5c8875832959d93ceb0fde25
$ ./hashcat -m 600 hash word --quiet
$
```

I didn't look too much into the source, but it seems you didn't add the typical _init, _update and _final functions required to make this work.

**Comment by DoZ10** [comment]
Oh. I tested with the test.sh script and added -w1 to OPTS options. 

How do you test them @jsteube ?

**Comment by jsteube** [comment]
The unit test has to be modified now that there's a pure kernel.

```
diff --git a/tools/test_modules/m00600.pm b/tools/test_modules/m00600.pm
index a96be237..8d188347 100644
--- a/tools/test_modules/m00600.pm
+++ b/tools/test_modules/m00600.pm
@@ -10,7 +10,7 @@ use warnings;
 
 use Digest::BLAKE2 qw (blake2b_hex);
 
-sub module_constraints { [[-1, -1], [-1, -1], [0, 55], [-1, -1], [-1, -1]] }
+sub module_constraints { [[0, 256], [-1, -1], [0, 55], [-1, -1], [-1, -1]] }
 
 sub module_generate_hash
 {
```

After this modification you can use test.sh but you also need to add the -P option in order to active the pure kernel testing mode.

**Comment by jsteube** [comment]
Updated with #2468 Many thanks for code base @DoZ10

**Pull request closed without merging**
