### PR TITLE
Hash-Mode 10500: set native_threads to 32 with Apple GPU's

### PR DESCRIPTION
**Pull request by matrix**
info here https://github.com/hashcat/hashcat/issues/3032#issuecomment-996726938

### CODE REVIEW

**Comment by phenotypic** [comment]
Hi @matrix thanks for your work, unfortunately this pull request fails `make` with the following errors:

```
src/modules/module_10500.c:153:3: error: use of undeclared identifier 'token_t'
  token_t token;
  ^
src/modules/module_10500.c:155:3: error: use of undeclared identifier 'token'
  token.token_cnt  = 12;
  ^
src/modules/module_10500.c:157:3: error: use of undeclared identifier 'token'
  token.signatures_cnt    = 1;
  ^
src/modules/module_10500.c:158:3: error: use of undeclared identifier 'token'
  token.signatures_buf[0] = SIGNATURE_PDF;
  ^
src/modules/module_10500.c:160:3: error: use of undeclared identifier 'token'
  token.len[0]     = 5;
  ^
src/modules/module_10500.c:161:3: error: use of undeclared identifier 'token'
  token.attr[0]    = TOKEN_ATTR_FIXED_LENGTH
  ^
src/modules/module_10500.c:164:3: error: use of undeclared identifier 'token'
  token.len_min[1] = 1;
  ^
src/modules/module_10500.c:165:3: error: use of undeclared identifier 'token'
  token.len_max[1] = 1;
  ^
src/modules/module_10500.c:166:3: error: use of undeclared identifier 'token'
  token.sep[1]     = '*';
  ^
src/modules/module_10500.c:167:3: error: use of undeclared identifier 'token'
  token.attr[1]    = TOKEN_ATTR_VERIFY_LENGTH
  ^
src/modules/module_10500.c:170:3: error: use of undeclared identifier 'token'
  token.len_min[2] = 1;
  ^
src/modules/module_10500.c:171:3: error: use of undeclared identifier 'token'
  token.len_max[2] = 1;
  ^
src/modules/module_10500.c:172:3: error: use of undeclared identifier 'token'
  token.sep[2]     = '*';
  ^
src/modules/module_10500.c:173:3: error: use of undeclared identifier 'token'
  token.attr[2]    = TOKEN_ATTR_VERIFY_LENGTH
  ^
src/modules/module_10500.c:176:3: error: use of undeclared identifier 'token'
  token.len_min[3] = 3;
  ^
src/modules/module_10500.c:177:3: error: use of undeclared identifier 'token'
  token.len_max[3] = 3;
  ^
src/modules/module_10500.c:178:3: error: use of undeclared identifier 'token'
  token.sep[3]     = '*';
  ^
src/modules/module_10500.c:179:3: error: use of undeclared identifier 'token'
  token.attr[3]    = TOKEN_ATTR_VERIFY_LENGTH
  ^
src/modules/module_10500.c:182:3: error: use of undeclared identifier 'token'
  token.len_min[4] = 1;
  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [modules/module_10500.so] Error 1
make: *** Waiting for unfinished jobs....
```

It would be great if the errors could be resolved and the PR could be merged. Thanks!

**Comment by matrix** [comment]
@phenotypic you are using an old version of hashcat. Retry with last github version and apply this patch if you want to try it

**Comment by phenotypic** [comment]
Ah yes my apologies, I've managed to solve it now.

Would be great if this could be merged into the latest version :)

**Comment by matrix** [comment]
merged in #3113

**Pull request closed without merging**
