### PR TITLE
Added hash-mode 26000 - OpenEdge Progress Encode

### PR DESCRIPTION
**Pull request by matrix**
see issue #2613

### CODE REVIEW

**Comment by lucidpsimc** [comment]
Thanks for working on this one Matrix. Is there a tutorial out there on what other changes have to be made in the repository for this to work? I tried adding the new files and installing to test it but it doesn't recognize -m 26000 yet.

**Comment by matrix** [comment]
> Thanks for working on this one Matrix. Is there a tutorial out there on what other changes have to be made in the repository for this to work? I tried adding the new files and installing to test it but it doesn't recognize -m 26000 yet.

Hi, the PR is still open, not merged yet.

You can use the branch in my repository to rebuild hashcat:
https://github.com/matrix/hashcat/tree/hash-mode-26000

Thanks

**Comment by lucidpsimc** [comment]
Thanks for the help. Using your repository and branch worked perfectly for my samples! Appreciate you helping out on this.

**Comment by jsteube** [comment]
Could you please update the mode to the next free one? 26000 was already used by Mozilla databases.

**Comment by matrix** [comment]
Hi, sure.
Please tell me what number do you prefer, so I can change it.

Thanks

**Comment by jsteube** [comment]
The next one would be 26200. Please also put the unit test, if possible.

**Comment by jsteube** [comment]
Many thanks, good work! I believe there's lots of potential for optimization. We can have a look at it if we're bored :)

**Pull request merged**
