### PR TITLE
Set up maximum length of example hash

### LINKED ISSUE #3382: make `--hash-info` readable again
After this commit https://github.com/hashcat/hashcat/pull/3321 and these changes https://github.com/hashcat/hashcat/issues/3359 (they fixed the reported problem, thanks @ventaquil ), I have a little problem with `--hash-info` (or old `--example-hashes`):

The problem is that this `--hash-info` was always nice to scroll and easy to read and search through, but after the changes with (mainly, but not limited to) the new `LUKS v1` format, it's difficult to scroll.

I'm talking about using `--hash-info` without `-m` switch, but it's also too much with the switch, I think.

My suggestion now is that we might consider changing this a little bit and have a limit on the hash lines we output... something we do with the normal "[s]tatus" prompt already.

My suggestion is to use something like this:

`hash_info_single ()`:
```C
char *tmp_line_buf;

hc_asprintf (&tmp_line_buf, "  Example.Hash........: %s", hashconfig->st_hash);

compress_terminal_line_length (tmp_line_buf, 24, 6); // 24 = strlen ("  Example.Hash........: ")

event_log_info (hashcat_ctx, "%s", tmp_line_buf);

hcfree (tmp_line_buf);
```

It uses `compress_terminal_line_length ()` in `src/terminal.c` .

The "only" problem I see with this that some user might need the full output, and for this problem I suggest that `--machine-readable` output remains unchanged.

Another problem I can see and I can kind of "forecast" is that some example hash output after this patch might seem to get too short or weird or that "too many hash types" get truncated (not only very, very long ones).

I think we could try it with the approach above or might discuss here even a better solution.

Any suggestion is welcome !
Thank you

### PR DESCRIPTION
**Pull request by ventaquil**
Fixes GH-3382

### CODE REVIEW

**Comment by ventaquil** [comment]
Example output

```
hashcat (v6.2.5-629-g336b9c38c) starting in hash-info mode

Hash Info:
==========

Hash mode #29311
  Name................: TrueCrypt RIPEMD160 + XTS 512 bit
  Category............: Full-Disk Encryption (FDE)
  Slow.Hash...........: Yes
  Password.Len.Min....: 0
  Password.Len.Max....: 64
  Salt.Type...........: Embedded
  Salt.Len.Min........: 0
  Salt.Len.Max........: 256
  Kernel.Type(s)......: pure
  Example.Hash.Format.: plain
  Example.Hash........: [too long example hash for your terminal, use --machine-readable]
                        $truecrypt$87914967f14737a67fb460f27b8aeb81de2b41bf2740b3dd78784e02763951daa47c7ca235e75c22ec8d959d6b67f7eedefad61e6a0d038079...
  Example.Pass........: hashcat
  Benchmark.Mask......: ?b?b?b?b?b?b?b
  Autodetect.Enabled..: Yes
  Self.Test.Enabled...: Yes
  Potfile.Enabled.....: Yes
  Custom.Plugin.......: No
  Plaintext.Encoding..: ASCII, HEX
```

Machine readable option stays unchanged.

```
hashcat (v6.2.5-629-g336b9c38c) starting in hash-info mode

{ "29311": { "name": "TrueCrypt RIPEMD160 + XTS 512 bit", "category": "Full-Disk Encryption (FDE)", "slow_hash": true, "password_len_min": 0, "password_len_max": 64, "is_salted": true, "salt_type": "embedded", "salt_len_min": 0, "salt_len_max": 256, "kernel_type": [ "pure" ], "example_hash_format": "plain", "example_hash": "$truecrypt$87914967f14737a67fb460f27b8aeb81de2b41bf2740b3dd78784e02763951daa47c7ca235e75c22ec8d959d6b67f7eedefad61e6a0d038079d3721a8e7215e4$15671e8c7b3dbed6453a114e6db89a52be9a9c1698a9c698f1e37f80d7afaf0efba82b6e5f5df32bd289b95343c6775e2c7f025ef1d8bfae84042a92546e15b635b5fade3aef6ee52a7a5ab018d33ea98bc115dfc62af606187fbab8cbda6e8417402c722ca8c2b07e6ca6a33bf94b2ce2a819a9f8cfaa5af70e3af6e5350d3a306f036f13ff5ba97d5728d5f6413b482c74f528211ae77b6c169215c5487d5a3ce23736b16996b86c71b12d120df28ef322f5143d9a258d0ae7aaa8c193a6dcb5bf18e3c57b5474d24b843f8dd4e83a74109396ddb4f0c50d3657a7eacc8828568e51202de48cd2dfe5acbe3d8840ade1ce44b716d5c0008f2b21b9981353cb12b8af2592a5ab744ae83623349f551acf371c81f86d17a8422654989f078179b2386e2aa8375853a1802cd8bc5d41ce45795f78b80e69fcfa3d14cf9127c3a33fa2dc76ad73960fb7bce15dd489e0b6eca7beed3733887cd5e6f3939a015d4d449185060b2f3bbad46e46d417b8f0830e91edd5ebc17cd5a99316792a36afd83fa1edc55da25518c8e7ff61e201976fa2c5fc9969e05cbee0dce7a0ef876b7340bbe8937c9d9c8248f0e0eae705fe7e1d2da48902f4f3e27d2cf532b7021e18", "example_pass": "hashcat", "benchmark_mask": "?b?b?b?b?b?b?b", "benchmark_charset1": "N/A", "autodetect_enabled": true, "self_test_enabled": true, "potfile_enabled": true, "custom_plugin": false, "plaintext_encoding": [ "ASCII", "HEX" ]
 } }
```

**Comment by jsteube** [comment]
The implementation is fine, but I think the default value of 128 is a bit too less. 

See:

```
$ ./hashcat --example-hashes | grep -i "too long" | wc -l
214
```

I'll merge this and update it in a later commit to a different default value.

**Comment by ventaquil** [comment]
I always check up option **Allow edits and access to secrets by maintainers** so as far as I know you can always add commits to my PR ([Allowing changes to a pull request branch created from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)).

Allow edits from maintainers

Also I forgot to add proper entry to `docs/changes.txt` - you can add one when you will change limit.

**Comment by jsteube** [comment]
OK, done https://github.com/hashcat/hashcat/commit/5fa08a79891056f396c5b0550b02dae0beac4a18

**Pull request merged**
