### PR TITLE
Add support for SHA-224

### PR DESCRIPTION
**Pull request by matrix**
#455 

```
$ ./hashcat -a3 -m 1300 b5b88539272856ba5c2924e93a46275a91245c2d9eb5673703b43f85 hash?a?a?a?a --quiet
b5b88539272856ba5c2924e93a46275a91245c2d9eb5673703b43f85:hashcat!
```

### CODE REVIEW

**Comment by jsteube** [comment]
Very nice, didn't expect that :)

2 things needs fixes:

- Please add mode for test.pl and test.sh (and test them)
- I see you move SHA256 -> SHA2, which is ok, but you should also move SHA384 and SHA512 then, because they are SHA2 as well

**Comment by matrix** [comment]
I will do :)
Thanks

**Comment by matrix** [comment]
Done ;)

```
$ ./tools/test.sh -m 1300 -T all -V 2 -a all
[ test_1481997672 ] > Init test for hash type 1300.
[ test_1481997672 ] [ Type 1300, Attack 0, Mode single, Device-Type Cpu + Gpu, Vector-Width 2 ] > OK : 0/31 not found, 0/31 not matched, 0/31 timeout
[ test_1481997672 ] [ Type 1300, Attack 1, Mode single, Device-Type Cpu + Gpu, Vector-Width 2 ] > OK : 0/30 not found, 0/30 not matched, 0/30 timeout
[ test_1481997672 ] [ Type 1300, Attack 3, Mode single, Device-Type Cpu + Gpu, Vector-Width 2 ] > OK : 0/8 not found, 0/8 not matched, 0/8 timeout
[ test_1481997672 ] [ Type 1300, Attack 6, Mode single, Device-Type Cpu + Gpu, Vector-Width 2 ] > OK : 0/7 not found, 0/7 not matched, 0/7 timeout
[ test_1481997672 ] [ Type 1300, Attack 7, Mode single, Device-Type Cpu + Gpu, Vector-Width 2 ] > OK : 0/7 not found, 0/7 not matched, 0/7 timeout
```

**Comment by jsteube** [comment]
Perfect!

**Pull request merged**
