### PR TITLE
Added hash-mode: sha256(md5(pass))

### PR DESCRIPTION
**Pull request by matrix**
added the algo proposed here #2103

### CODE REVIEW

**Comment by philsmd** [comment]
didn't look at the code yet. but docs/changes.txt and docs/readme.txt changes are missing for sure

**Comment by jsteube** [comment]
Please update hash-mode number to next one free, 4710 can't be used since 4700 is used. 4710 would be salted version of 4700.

**Comment by matrix** [comment]
> Please update hash-mode number to next one free, 4710 can't be used since 4700 is used. 4710 would be salted version of 4700.

ok, could you give me a list of free hash-mode to be used ? thanks!

**Comment by matrix** [comment]
done

**Pull request merged**
