### PR TITLE
Added Python Werkzeug MD5 module

### PR DESCRIPTION
**Pull request by mdawsonuk**
Continuing to iterate over hash formats raised in https://github.com/hashcat/hashcat/issues/3205 this one is MD5 (identical to -m 60)

Due to the hash being exclusive to Werkzeug, this is marked as HASH_CATEGORY_FRAMEWORK.

### CODE REVIEW

**Comment by ventaquil** [comment]
> identical to -m 60

What is purpose to add identical module - just with different name?

**Comment by mdawsonuk** [comment]
Different hash format, requested in the referenced issue

**Comment by ventaquil** [comment]
Then maybe it's a good idea to make common part of signature like

```c
static const char *ST_HASH        = "werkzeug$md5$84143$7f51edecfa6fb401a0b5e63d33fc8c0e";
```

instead of simple

```c
static const char *ST_HASH        = "md5$84143$7f51edecfa6fb401a0b5e63d33fc8c0e";
```

**Comment by mdawsonuk** [comment]
Perhaps I'm missing something but that's just not the format that the hash it in. It will always be in the format `md5$salt$hash`.

I've had discussions around whether this should be part of the same module as the kernel is (in this case mode 60) but it was agreed that it is more user-friendly to have it as a separate module.

**Pull request merged**
