### PR TITLE
Replaced --example-hashes with --hash-info

### PR DESCRIPTION
**Pull request by matrix**
Hi,
I have replaced the --example-hashes option with --hash-info, which also returns some additional information (using an output format similar to the --backend-info / -I option).
To maintain backward compatibility, I set --example-hashes with an alias of --hash-info.

before

```
$ ./hashcat -m 1000 --example
hashcat (v6.1.1-120-g15bf8b730) starting...

MODE: 1000
TYPE: NTLM
HASH: b4b9b02e6f09a9bd760f388b67351e2b
PASS: hashcat
```

after

```
$ ./hashcat -m 1000 --hash-info
hashcat (v6.1.1-122-g77e328d65) starting...

Hash Info:
==========

Hash mode #1000
  Name................: NTLM
  Category............: Operating System
  Password.Len.Min....: 0
  Password.Len.Max....: 256
  Hashes.Count.Min....: 1
  Hashes.Count.Max....: 4294967295
  Kernel.Type(s)......: pure optimized
  Example.Hash.Format.: plain
  Example.Hash........: b4b9b02e6f09a9bd760f388b67351e2b
  Example.Pass........: hashcat
  Benchmark.Mask......: ?b?b?b?b?b?b?b

```

### CODE REVIEW

**Comment by matrix** [comment]
New example output after last commit:

```
Hash Info:
==========

Hash mode #2500
  Name................: WPA-EAPOL-PBKDF2
  Category............: Network Protocols
  Slow.Hash...........: Yes
  Password.Len.Min....: 8
  Password.Len.Max....: 63
  Salt.Type...........: Embedded
  Salt.Len.Min........: 0
  Salt.Len.Max........: 256
  Hashes.Count.Min....: 1
  Hashes.Count.Max....: 4294967295
  Kernel.Type(s)......: pure 
  Example.Hash.Format.: hex-encoded
  Example.Hash........: 4843505804000000000235380000000000000000000000000000000000000000000000000000000000000151aecc428f182acefbd1a9e62d369a079265784da83ba4cf88375c44c830e6e5aa5d6faf352aa496a9ee129fb8292f7435df5420b823a1cd402aed449cced04f552c5b5acfebf06ae96a09c96d9a01c443a17aa62258c4f651a68aa67b0001030077fe010900200000000000000001a4cf88375c44c830e6e5aa5d6faf352aa496a9ee129fb8292f7435df5420b8230000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018dd160050f20101000050f20201000050f20201000050f20200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  Example.Pass........: hashcat!
  Benchmark.Mask......: ?a?a?a?a?a?a?a?a

```

**Comment by davidbolvansky** [comment]
Cool! What do you think about machine readable output?

**Comment by matrix** [comment]
> Cool! What do you think about machine readable output?

if and as soon as the merge is done, I will add it

**Comment by jsteube** [comment]
Great PR. Thanks!

I'll merge as-is, but if possible, please also add missing entry to extra/tab_completion/hashcat.sh

**Comment by jsteube** [comment]
Also some compiler warnings needs a fix:

```
src/terminal.c: In function ‘hash_info_single’:
src/terminal.c:570:38: warning: ‘strncat’ specified bound 5 equals source length [-Wstringop-overflow=]
  570 |     if (hashconfig->has_pure_kernel) strncat (kernel_types, "pure ", 5);
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/terminal.c:571:43: warning: ‘strncat’ specified bound 9 equals source length [-Wstringop-overflow=]
  571 |     if (hashconfig->has_optimized_kernel) strncat (kernel_types, "optimized", 9);
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I fixed it as well as did the change to extra/tab_completion/hashcat.sh with commit: https://github.com/hashcat/hashcat/commit/6daea9c7c1c7bcb5d8943083fde5f3e86c3d30b8

**Pull request merged**
