### PR TITLE
Unit tests: add test modules for hash-modes 31500 and 31600 and handle them in tools/test.pl

### PR DESCRIPTION
**Pull request by matrix**
Added missing test modules for PR #3656 and #3657 

@Chick3nman I tested them very quickly and they seem to be working. Would you be able to run test.sh for your new hash-modes?

Thanks ;)

### CODE REVIEW

**Comment by Chick3nman** [comment]
Hey, thanks for the help! Yeah, I'll give this a check and make sure it's all working.

**Comment by Chick3nman** [comment]
Every appears to be ok, the test modules are nearly identical to 1100 and 2100 anyway, just with the NTLM hash change.

**Comment by matrix** [comment]
> Every appears to be ok, the test modules are nearly identical to 1100 and 2100 anyway, just with the NTLM hash change.

Also test.pl was modified

**Comment by Chick3nman** [comment]
> > Every appears to be ok, the test modules are nearly identical to 1100 and 2100 anyway, just with the NTLM hash change.
> 
> Also test.pl was modified

Yes I saw, I don't see any issues

**Comment by jsteube** [comment]
So far we managed to keep out hash-mode specific stuff out of generic code. If you really need changes to test.pl to get it working, find a more generic approach, maybe using hooks.

**Comment by matrix** [comment]
What do you mean by hooks on test.pl? If you got an idea give us an example :)

**Comment by matrix** [comment]
Ok, I found the undocumented function to do what you said

**Comment by matrix** [comment]
test.sh output

```
bash-3.2$ ./tools/test.sh -m 31500 -f -d 1
[ test_1684439959 ] > Init test for hash type 31500.
[ test_1684439959 ] [ Type 31500, Attack 0, Mode single, Device-Type Gpu, Kernel-Type Optimized, Vector-Width 1 ] > OK : 0/8 not found, 0/8 not matched, 0/8 timeout, 0/8 skipped
[ test_1684439959 ] [ Type 31500, Attack 0, Mode single, Device-Type Gpu, Kernel-Type Optimized, Vector-Width 4 ] > OK : 0/8 not found, 0/8 not matched, 0/8 timeout, 0/8 skipped
bash-3.2$ ./tools/test.sh -m 31600 -f -d 1
[ test_1684439996 ] > Init test for hash type 31600.
[ test_1684439996 ] [ Type 31600, Attack 0, Mode single, Device-Type Gpu, Kernel-Type Optimized, Vector-Width 1 ] > OK : 0/8 not found, 0/8 not matched, 0/8 timeout, 0/8 skipped
[ test_1684439996 ] [ Type 31600, Attack 0, Mode single, Device-Type Gpu, Kernel-Type Optimized, Vector-Width 4 ] > OK : 0/8 not found, 0/8 not matched, 0/8 timeout, 0/8 skipped
```

**Comment by jsteube** [comment]
Fantastic, thanks!

**Pull request merged**
