### PR TITLE
Added guess data into --status-json output to fix #3061

### LINKED ISSUE #3061: --status-json does not include attack info
**Describe the feature**
`--status-json` should include attack info

**Current behavior**
`--status-json` does not include attack info

**Expected behavior**
`--status-json` to include attack info: such as guess.mod, guess,queue, etc...

**Hashcat version**
 - Version:  tested with 6.2.4, checked [master](https://github.com/hashcat/hashcat/blob/bf865d8bff2db0d7cc617c3fd5d8e73bd1b4a8b3/src/terminal.c#L1248-L1365) branch too, the feature does not exist yet

### PR DESCRIPTION
**Pull request by b0lek**
Fix for #3061
Updated `changes.txt` for #3061 and #3050

### CODE REVIEW

**Comment by s77rt** [comment]
can `guess_base_count` be set if `guess_base` is not?
or will it just be null?
can you provide some tested outputs

**Comment by b0lek** [comment]
Below you have some tested outputs.
- all variables are always present
- you need to interpret values
- `null` value is possible only for `guess_base` or `guess_mod`
- if `"guess_base": null` then `"guess_base_count": "0"`
See examples:

`{ "session": "hashcat", "guess": { "guess_base": "./test.dic", "guess_base_count": "1", "guess_base_offset": "1", "guess_base_percent": "100.00%", "guess_mask_length": "-1", "guess_mod": null, "guess_mod_count": "1", "guess_mod_offset": "1", "guess_mod_percent": "100.00%", "guess_mode": "1" } "status": 6, "target": "some hash here", "progress": [13, 13], "restore_point": 0, "recovered_hashes": [1, 1], "recovered_salts": [1, 1], "rejected": 0, "devices": [ { "device_id": 1, "speed": 16329, "temp": 48, "util": 12 } ], "time_start": 1639831526, "estimated_stop": 1639831526 }`

`{ "session": "hashcat", "guess": { "guess_base": "./test.dic", "guess_base_count": "1", "guess_base_offset": "1", "guess_base_percent": "100.00%", "guess_mask_length": "-1", "guess_mod": null, "guess_mod_count": "1", "guess_mod_offset": "1", "guess_mod_percent": "100.00%", "guess_mode": "1" } "status": 5, "target": "./test.txt", "progress": [13, 13], "restore_point": 13, "recovered_hashes": [0, 2], "recovered_salts": [0, 1], "rejected": 0, "devices": [ { "device_id": 1, "speed": 8652, "temp": 48, "util": 4 } ], "time_start": 1639831451, "estimated_stop": 1639831451 }`

`{ "session": "hashcat", "guess": { "guess_base": "?1?2?2", "guess_base_count": "15", "guess_base_offset": "3", "guess_base_percent": "20.00%", "guess_mask_length": "3", "guess_mod": null, "guess_mod_count": "1", "guess_mod_offset": "1", "guess_mod_percent": "100.00%", "guess_mode": "10" } "status": 5, "target": "./test.txt", "progress": [80352, 80352], "restore_point": 1296, "recovered_hashes": [0, 2], "recovered_salts": [0, 1], "rejected": 0, "devices": [ { "device_id": 1, "speed": 1024824, "temp": 51, "util": 4 } ], "time_start": 1639831185, "estimated_stop": 1639831185 }`

`{ "session": "hashcat", "guess": { "guess_base": "?1?2?2?2?2", "guess_base_count": "15", "guess_base_offset": "5", "guess_base_percent": "33.33%", "guess_mask_length": "5", "guess_mod": null, "guess_mod_count": "1", "guess_mod_offset": "1", "guess_mod_percent": "100.00%", "guess_mode": "10" } "status": 5, "target": "./test.txt", "progress": [104136192, 104136192], "restore_point": 1679616, "recovered_hashes": [0, 2], "recovered_salts": [0, 1], "rejected": 0, "devices": [ { "device_id": 1, "speed": 91510784, "temp": 52, "util": 67 } ], "time_start": 1639831186, "estimated_stop": 1639831187 }`

`{ "session": "hashcat", "guess": { "guess_base": null, "guess_base_count": "0", "guess_base_offset": "1", "guess_base_percent": "0.00%", "guess_mask_length": "-1", "guess_mod": "rules/best64.rule", "guess_mod_count": "1", "guess_mod_offset": "1", "guess_mod_percent": "100.00%", "guess_mode": "5" } "status": 3, "target": "hash goes here", "progress": [0, 0], "restore_point": 0, "recovered_hashes": [0, 1], "recovered_salts": [0, 1], "rejected": 0, "devices": [ { "device_id": 1, "speed": 0, "temp": 50, "util": 0 } ], "time_start": 1639834506, "estimated_stop": 1639834516 }`

**Comment by s77rt** [comment]
`guess_base_count` is 0 but `guess_base_offset` is 1 .. that's weird

also numbers should be outputted as numbers
example:
`"guess_mode": "5"` should be `"guess_mode": 5`

**Comment by b0lek** [comment]
Numbers fixed and I have removed % sign from percentage values.
I don't want to change how the values are calculated as this might impact other places. Just JSON printout is modified here.
So now it will look like this:

`{ "session": "hashcat", "guess": { "guess_base": "?1?2?2?2", "guess_base_count": 15, "guess_base_offset": 4, "guess_base_percent": 26.67, "guess_mask_length": 4, "guess_mod": null, "guess_mod_count": 1, "guess_mod_offset": 1, "guess_mod_percent": 100.00, "guess_mode": 10 }, "status": 5, "target": "8743b52063cd84097a65d1633f5c74f5", "progress": [2892672, 2892672], "restore_point": 46656, "recovered_hashes": [0, 1], "recovered_salts": [0, 1], "rejected": 0, "devices": [ { "device_id": 1, "speed": 89910055, "temp": 56, "util": 79 } ], "time_start": 1639841782, "estimated_stop": 1639841782 }`

`{ "session": "hashcat", "guess": { "guess_base": null, "guess_base_count": 0, "guess_base_offset": 1, "guess_base_percent": 0.00, "guess_mask_length": -1, "guess_mod": "rules/best64.rule", "guess_mod_count": 1, "guess_mod_offset": 1, "guess_mod_percent": 100.00, "guess_mode": 5 }, "status": 3, "target": "8743b52063cd84097a65d1633f5c74f5", "progress": [0, 0], "restore_point": 0, "recovered_hashes": [0, 1], "recovered_salts": [0, 1], "rejected": 0, "devices": [ { "device_id": 1, "speed": 0, "temp": 47, "util": 0 } ], "time_start": 1639843105, "estimated_stop": 1639843114 }`

**Review by Chick3nman — APPROVED** [review]

**Pull request merged**
