### PR TITLE
use dlfcn, even on Windows

### PR DESCRIPTION
**Pull request by neheb**
There's such a library on MSYS2. Use it.

Fun fact: the so called Windows CI currently in use does not test Windows but Cygwin.

### CODE REVIEW

**Comment by jsteube** [comment]
Doesn't work for me:

```
root@ht:~/hashcat# make win
x86_64-w64-mingw32-gcc   -std=gnu99 -W -Wall -Wextra -O2 -pipe -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib -Ideps/zlib/contrib -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash -DWITH_CUBIN -Ideps/unrar -fPIC -I/opt/win-iconv-64/include/ -DWITH_HWMON -D__USE_MINGW_ANSI_STDIO=0   -c -o obj/affinity.WIN.o src/affinity.c
x86_64-w64-mingw32-gcc   -std=gnu99 -W -Wall -Wextra -O2 -pipe -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib -Ideps/zlib/contrib -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash -DWITH_CUBIN -Ideps/unrar -fPIC -I/opt/win-iconv-64/include/ -DWITH_HWMON -D__USE_MINGW_ANSI_STDIO=0   -c -o obj/autotune.WIN.o src/autotune.c
x86_64-w64-mingw32-gcc   -std=gnu99 -W -Wall -Wextra -O2 -pipe -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib -Ideps/zlib/contrib -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash -DWITH_CUBIN -Ideps/unrar -fPIC -I/opt/win-iconv-64/include/ -DWITH_HWMON -D__USE_MINGW_ANSI_STDIO=0   -c -o obj/backend.WIN.o src/backend.c
x86_64-w64-mingw32-gcc   -std=gnu99 -W -Wall -Wextra -O2 -pipe -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib -Ideps/zlib/contrib -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash -DWITH_CUBIN -Ideps/unrar -fPIC -I/opt/win-iconv-64/include/ -DWITH_HWMON -D__USE_MINGW_ANSI_STDIO=0   -c -o obj/benchmark.WIN.o src/benchmark.c
x86_64-w64-mingw32-gcc   -std=gnu99 -W -Wall -Wextra -O2 -pipe -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib -Ideps/zlib/contrib -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash -DWITH_CUBIN -Ideps/unrar -fPIC -I/opt/win-iconv-64/include/ -DWITH_HWMON -D__USE_MINGW_ANSI_STDIO=0   -c -o obj/bitmap.WIN.o src/bitmap.c
x86_64-w64-mingw32-gcc   -std=gnu99 -W -Wall -Wextra -O2 -pipe -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib -Ideps/zlib/contrib -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash -DWITH_CUBIN -Ideps/unrar -fPIC -I/opt/win-iconv-64/include/ -DWITH_HWMON -D__USE_MINGW_ANSI_STDIO=0   -c -o obj/bitops.WIN.o src/bitops.c
x86_64-w64-mingw32-gcc   -std=gnu99 -W -Wall -Wextra -O2 -pipe -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib -Ideps/zlib/contrib -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash -DWITH_CUBIN -Ideps/unrar -fPIC -I/opt/win-iconv-64/include/ -DWITH_HWMON -D__USE_MINGW_ANSI_STDIO=0   -c -o obj/combinator.WIN.o src/combinator.c
x86_64-w64-mingw32-gcc   -std=gnu99 -W -Wall -Wextra -O2 -pipe -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib -Ideps/zlib/contrib -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash -DWITH_CUBIN -Ideps/unrar -fPIC -I/opt/win-iconv-64/include/ -DWITH_HWMON -D__USE_MINGW_ANSI_STDIO=0   -c -o obj/common.WIN.o src/common.c
x86_64-w64-mingw32-gcc   -std=gnu99 -W -Wall -Wextra -O2 -pipe -Iinclude/ -IOpenCL/ -Ideps/LZMA-SDK/C -Ideps/zlib -Ideps/zlib/contrib -Ideps/OpenCL-Headers -DWITH_BRAIN -Ideps/xxHash -DWITH_CUBIN -Ideps/unrar -fPIC -I/opt/win-iconv-64/include/ -DWITH_HWMON -D__USE_MINGW_ANSI_STDIO=0   -c -o obj/convert.WIN.o src/convert.c
In file included from src/backend.c:24:
include/dynloader.h:11:10: fatal error: dlfcn.h: No such file or directory
   11 | #include <dlfcn.h>
      |          ^~~~~~~~~
```

**Comment by neheb** [comment]
Ah right. Library path needs to be added.

edit: do you have dlfcn installed?

**Comment by jsteube** [comment]
No, is that a separate package?

**Comment by neheb** [comment]
Yes.

**Comment by neheb** [comment]
https://packages.msys2.org/package/mingw-w64-x86_64-dlfcn

edit: On Fedora it shows up as mingw64-dlfcn

**Comment by jsteube** [comment]
It doesn't exist on Ubuntu 22.04

**Comment by neheb** [comment]
https://pkgs.org/search/?q=dlfcn

Unfortunate.

**Pull request closed without merging**
