### PR TITLE
Added hash-mode: BitShares v0.x - sha512(sha512(pass))

### PR DESCRIPTION
**Pull request by matrix**
Details here #1572

### CODE REVIEW

**Comment by jsteube** [comment]
Please update hash-mode number and remove entries from docs/* as described in the previous PR (send it later in full to avoid conflict after PR merge).

**Comment by jsteube** [comment]
In -a 3 mode with pure kernel I'm getting this error:

```
main_kernel(65): error: argument of type "sha512_ctx_t *" is incompatible with parameter of type "sha512_ctx_vector_t *"
```

The optimized kernel works fine.

**Comment by matrix** [comment]
I pushed the fix but I don't see the new patch here ...

**Comment by matrix** [comment]
https://github.com/matrix/hashcat/commit/d045c0f62a837bd741cf47d4ee6d6f0f72cfab72

**Comment by matrix** [comment]
done

**Pull request merged**
