### PR TITLE
fixes #1117: added -m 22100 = BitLocker

### LINKED ISSUE #1117: add support for Bitlocker
Placeholder for adding Bitlocker support.

Spec that might provide enough info: https://github.com/libyal/libbde/blob/master/documentation/BitLocker%20Drive%20Encryption%20(BDE)%20format.asciidoc

As requested in this older forums thread: https://hashcat.net/forum/thread-5474.html

### PR DESCRIPTION
**Pull request by philsmd**
I have implemented this new module and hash type. $bitlocker$0$... and $bitlocker$1$... hashes should now be working.

Thank you all and all the best for the year 2020 !

### CODE REVIEW

**Comment by jsteube** [comment]
Super nice!

**Comment by roycewilliams** [comment]
@philsmd does this represent all major BitLocker hash subtypes, or are there others not represented here?

**Comment by jsteube** [comment]
@roycewilliams It's all user password based ones

**Comment by ventaquil** [comment]
Congratulations! You should apply note that it's only AES-256 CCM mode (as far as I know).

What about minimum password length? [Here you have](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-group-policy-settings) information about minimum password length: _"Passwords must be at least 8 characters"_.
I checked settings in Local Group Policy Editor and I cannot set password length less than 8 characters.

**Comment by kolet** [comment]
god damn ! nice.
finally :)

btw , what/how to extract for this to get the hash ? 
like whats the way of getting that hash from a bitlocker drive

**Comment by ventaquil** [comment]
@kolet you have extractor in [magnumripper/JohnTheRipper](https://github.com/magnumripper/JohnTheRipper) repo ([src/bitlocker2john.c](https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/src/bitlocker2john.c) file).

Note that it seems to doesn't work with encrypted VHDX files with dynamic resize option.

**Pull request merged**
