### PR TITLE
Add BLAKE2b-512($salt.$pass) and BLAKE2b-512($pass.$salt)

### PR DESCRIPTION
**Pull request by tweqx**
This pull request adds the hash modes 610 and 620, respectively "BLAKE2b-512($pass.$salt)" and "BLAKE2b-512($salt.$pass)".

I took heavy inspiration from the hash modes 600 (BLAKE2b), 10 (md5($pass.$salt)) and 20 (md5($salt.$pass)).

I'll post a benchmark of the two modes soon.

### CODE REVIEW

**Comment by tweqx** [comment]
Benchmark for the hash mode 610, BLAKE2b-512($salt.$pass): (mode 90001 below)
```
hashcat (v6.2.5-432-gd4a8c7e57) starting in benchmark mode

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #2: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
CUDA API (CUDA 11.7)
====================
* Device #1: NVIDIA GeForce RTX 3060, 11281/12287 MB, 28MCU

OpenCL API (OpenCL 3.0 CUDA 11.7.57) - Platform #1 [NVIDIA Corporation]
=======================================================================
* Device #2: NVIDIA GeForce RTX 3060, skipped

OpenCL API (OpenCL 3.0 ) - Platform #2 [Intel(R) Corporation]
=============================================================
* Device #3: Intel(R) UHD Graphics 730, 3200/6468 MB (1617 MB allocatable), 24MCU

Benchmark relevant options:
===========================
* --optimized-kernel-enable

--------------------------------------------
* Hash-Mode 90001 (BLAKE2b-512($pass.$salt))
--------------------------------------------

Speed.#1.........:  1963.0 MH/s (59.54ms) @ Accel:128 Loops:1024 Thr:32 Vec:1
Speed.#3.........: 73143.4 kH/s (84.55ms) @ Accel:256 Loops:16 Thr:64 Vec:1
Speed.#*.........:  2036.2 MH/s

Started: Sun May 22 12:27:33 2022
Stopped: Sun May 22 12:27:50 2022
```

Benchmark for the hash mode 620, BLAKE2b-512($salt.$pass): (mode 90000 below)
```
hashcat (v6.2.5-432-gd4a8c7e57) starting in benchmark mode

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #2: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
CUDA API (CUDA 11.7)
====================
* Device #1: NVIDIA GeForce RTX 3060, 11281/12287 MB, 28MCU

OpenCL API (OpenCL 3.0 CUDA 11.7.57) - Platform #1 [NVIDIA Corporation]
=======================================================================
* Device #2: NVIDIA GeForce RTX 3060, skipped

OpenCL API (OpenCL 3.0 ) - Platform #2 [Intel(R) Corporation]
=============================================================
* Device #3: Intel(R) UHD Graphics 730, 3200/6468 MB (1617 MB allocatable), 24MCU

Benchmark relevant options:
===========================
* --optimized-kernel-enable

--------------------------------------------
* Hash-Mode 90000 (BLAKE2b-512($salt.$pass))
--------------------------------------------

Speed.#1.........:  1836.4 MH/s (63.64ms) @ Accel:16 Loops:512 Thr:512 Vec:1
Speed.#3.........: 67403.5 kH/s (91.74ms) @ Accel:512 Loops:16 Thr:32 Vec:1
Speed.#*.........:  1903.8 MH/s

Started: Sun May 22 12:27:19 2022
Stopped: Sun May 22 12:27:28 2022
```

**Comment by jsteube** [comment]
Hey there, many thanks for the contribution. Typically before I review the code in detail I'm running the unit tests to check if everything works as it should. So I did this:

```
$ tools/test.sh -t multi -a 0 -m 620 -V1 -P
```

And I've received the following unexpected results:

```
[ test_1653311624 ] > Init test for hash type 620.
[ test_1653311624 ] [ Type 620, Attack 0, Mode multi,  Device-Type Gpu, Kernel-Type Pure, Vector-Width 1 ] > Error : 1/1 not found, 0/1 not matched, 0/1 timeout, 0/1 skipped
```

So far I did not look into any of the code. I am wondering did you try these tests locally and it worked for you?

**Comment by tweqx** [comment]
Thanks for your comment.
I didn't run the unit tests, I guess I should have read the development guide more thoroughly.
Running the command you posted (and adding `-D 1` as I don't have a GPU configured) gives:
```
[ test_1653315077 ] > Init test for hash type 620.
[ test_1653315077 ] [ Type 620, Attack 0, Mode multi,  Device-Type Cpu, Kernel-Type Pure, Vector-Width 1 ] > Error : 0/1 not found, 1/1 not matched, 0/1 timeout, 0/1 skipped
```
So, a different error than yours. The "not matched" is an error comes from missing calls to `lc` in the test-unit perl code (that's what the latest commit added). After fixing this, the command gives what looks to be the expected result:
```
[ test_1653316347 ] > Init test for hash type 620.
[ test_1653316347 ] [ Type 620, Attack 0, Mode multi,  Device-Type Cpu, Kernel-Type Pure, Vector-Width 1 ] > OK : 0/1 not found, 0/1 not matched, 0/1 timeout, 0/1 skipped
```
I have no idea why you have a "not found" error though.

**Comment by jsteube** [comment]
I can see already many problems fixed so far, but a few are left. 

Here's a log:

```
[ test_1653489490 ] > Init test for hash type 610.
[ test_1653489490 ] [ Type 610, Attack 1, Mode single, Device-Type Gpu, Kernel-Type Optimized, Vector-Width 4 ] > Error : 1/7 not found, 0/7 not matched, 0/7 timeout, 0/7 skipped
[ test_1653489490 ] [ Type 610, Attack 1, Mode multi,  Device-Type Gpu, Kernel-Type Optimized, Vector-Width 4 ] > OK : 0/1 not found, 0/1 not matched, 0/1 timeout, 0/1 skipped
[ test_1653489511 ] > Init test for hash type 610.
[ test_1653489511 ] [ Type 610, Attack 3, Mode single, Device-Type Gpu, Kernel-Type Optimized, Vector-Width 4 ] > OK : 0/7 not found, 0/7 not matched, 0/7 timeout, 0/7 skipped
! unhandled return code, see test_1653489511/logfull.txt or test_1653489511/test_report.log for details.
[ test_1653489511 ] [ Type 610, Attack 3, Mode multi,  Device-Type Gpu, Kernel-Type Optimized, Vector-Width 4 ] > Error : 1/1 not found, 0/1 not matched, 0/1 timeout, 0/1 skipped
```

and same on CPU

```
[ test_1653489947 ] > Init test for hash type 610.
[ test_1653489947 ] [ Type 610, Attack 1, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1 ] > Error : 1/7 not found, 0/7 not matched, 0/7 timeout, 0/7 skipped
[ test_1653489947 ] [ Type 610, Attack 1, Mode multi,  Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1 ] > OK : 0/1 not found, 0/1 not matched, 0/1 timeout, 0/1 skipped
[ test_1653489970 ] > Init test for hash type 610.
[ test_1653489970 ] [ Type 610, Attack 3, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1 ] > OK : 0/7 not found, 0/7 not matched, 0/7 timeout, 0/7 skipped
! unhandled return code, see test_1653489970/logfull.txt or test_1653489970/test_report.log for details.
[ test_1653489970 ] [ Type 610, Attack 3, Mode multi,  Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1 ] > Error : 1/1 not found, 0/1 not matched, 0/1 timeout, 0/1 skipped
```



The error was:

```
> Testing hash type 610 with attack mode 3, markov enabled, multi hash, Device-Type Gpu, Kernel-Type Optimized, Vector-Width 4.
* Device #1: ATTENTION! CUDA kernel self-test failed.

Your device driver installation is probably broken.
See also: https://hashcat.net/faq/wrongdriver

Aborting session due to kernel self-test failure.

You can use --self-test-disable to override, but do not report related errors.
! unhandled return code 255, cmdline : ./hashcat --quiet --potfile-disable --hwmon-disable -O --runtime 400 -D 2 --backend-vector-width 4 -a 3 -m 610  test_1653489511/610_multihash_bruteforce.txt test_1653489511/610_passwords.txt
```

Please retry with the same settings on your system, it should also error on CPU only (that's the ones with the -D1).  

Command used:

```
tools/test.sh -t all -a 3 -m 610 -V4 -O
tools/test.sh -t all -a 3 -m 610 -V1 -O -D1
```

**Comment by tweqx** [comment]
Thanks.
The last two commits fixed two bugs that caused some unit tests to fail; having fixed these two bugs `./tools/test.sh -a all -V all -m 610 -t all -D 1` report no failure.
`./tools/test.sh -a all -V all -m 620 -t all -D 1` already passed previously, so I think everything is now working as it should. I'm sorry for the inconvenience, I should have made sure the tests passed before opening the pull request in the first place.

**Comment by jsteube** [comment]
Hey there, many thanks for the fixes and no worries, that's perfectly normal :)

**Pull request merged**
