### PR TITLE
Add zlib support to load hashlist/wordlist

### PR DESCRIPTION
**Pull request by matrix**
Patch from #1848 adapted to hash-mode-plugin branch

### CODE REVIEW

**Comment by jsteube** [comment]
As discussed, please use LZMA instead.

**Comment by matrix** [comment]
> As discussed, please use LZMA instead.

I think to add also the LZMA support, but don't put in queue this pull request. It could become too big to review.

**Comment by matrix** [comment]
I need to push also the zlib github repository in deps ? (I see lzma SDK it's statically include into that folder)

**Comment by jsteube** [comment]
No that's the reason why I cannot accept the PR because I don't want the zlib SDK deps. For LZMA, currently it's just parts of the LZMA SDK. Please add the remaining files from original LZMA SDK which you need for decompression. If you do not want to update the current PR, please close it and create a new one for LZMA.

**Pull request closed without merging**
