### PR TITLE
Added hash-mode: MetaMask Wallet

### PR DESCRIPTION
**Pull request by matrix**
see #2818

### CODE REVIEW

**Comment by dialap** [comment]
Greetings, thank you for your excellent work. Can you please tell me how to install this update? Made a clone there files are not updated, added manually to folders, built with MSYS2, 26600 algorithm is not defined(
And what format should I use? hash:iv:salt?

**Comment by matrix** [comment]
> Greetings, thank you for your excellent work. Can you please tell me how to install this update? Made a clone there files are not updated, added manually to folders, built with MSYS2, 26600 algorithm is not defined(

Check here: https://github.com/hashcat/hashcat/issues/2818#issuecomment-873616674

**Comment by jsteube** [comment]
The self-test is failing:

```
root@ht:~/hashcat# tools/test.sh -t multi -a 0 -m 26600 -V 4  
[ test_1625468734 ] > Init test for hash type 26600.
[ test_1625468734 ] [ Type 26600, Attack 0, Mode multi,  Device-Type Gpu, Kernel-Type Optimized, Vector-Width 4 ] > Error : 0/1 not found, 1/1 not matched, 0/1 timeout
```

Not matched is typically a problem in encode() function, maybe missing swap or so. Please fix!

**Comment by matrix** [comment]
> The self-test is failing:
> 
> ```
> root@ht:~/hashcat# tools/test.sh -t multi -a 0 -m 26600 -V 4  
> [ test_1625468734 ] > Init test for hash type 26600.
> [ test_1625468734 ] [ Type 26600, Attack 0, Mode multi,  Device-Type Gpu, Kernel-Type Optimized, Vector-Width 4 ] > Error : 0/1 not found, 1/1 not matched, 0/1 timeout
> ```
> 
> Not matched is typically a problem in encode() function, maybe missing swap or so. Please fix!

Hi, it should now work

**Comment by jsteube** [comment]
I'm going to merge because it's already working great. But you might want to add metamask2hashcat.py or something. Not sure every user will understand which parts to copy where.

**Comment by RNOVAKOSKY** [comment]
Obs.: at the moment, this is the syntax of Hash Target (need to get from VAULT Metamak), so HashCat works fine:
**'$' + 'metamask' + '$' + [salt] + '$' + [iv] + '$' + [data]**
or use the extration tool to get this fields from VAULT

**Pull request merged**
