### PR TITLE
Added hash-mode: Stuffit5

### PR DESCRIPTION
**Pull request by matrix**
Details in #2698 

thanks to @gregesposito for cooperation

```
CUDA API (CUDA 11.2)
====================
* Device #1: GeForce GTX 1080 Ti, 11031/11178 MB, 28MCU

OpenCL API (OpenCL 1.2 CUDA 11.2.66) - Platform #1 [NVIDIA Corporation]
=======================================================================
* Device #2: GeForce GTX 1080 Ti, skipped

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Hashmode: 29800 - Stuffit5

Speed.#1.........: 11735.9 MH/s (78.83ms) @ Accel:64 Loops:512 Thr:1024 Vec:1

Started: Thu Feb  4 01:13:07 2021
Stopped: Thu Feb  4 01:13:18 2021

```

### CODE REVIEW

**Comment by jsteube** [comment]
Small note, I have renamed the hash-mode from 29800 to 24700.

Please see commit for some other small changes: https://github.com/hashcat/hashcat/commit/b3bfaf8e1e4828d8047d9951aeac3119761f7642

Thanks for the contribution @matrix and @gregesposito

**Comment by Double-A-92** [comment]
Does anybody know how to actually make use of this? 
If I have a .sit file how do I get the hash out of it to try to crack it with this?

**Comment by gregesposito** [comment]
> Does anybody know how to actually make use of this? If I have a .sit file how do I get the hash out of it to try to crack it with this?

Place your hash in a hash.txt file and run:

hashcat.exe -m24700 -a3 -o cracked.txt hash.txt –keep-guessing

You will get a number of possibilities, any should work, but if you want the original password you may need to run for a while.

If you need any further help, do reach out to me, I run Stuffit recoveries for people all the time!

**Comment by Double-A-92** [comment]
I didn't know how to even find the Hash of the original file.

In the meantime I found one of your comment in a blog though:

> The hashes are locatable with a hexeditor as seen in this pic – always stuck between 00-05 and the A5-A5-A5-A5 characters.
File-Comparison-blog

**Pull request merged**
