### PR TITLE
hashcat API

### PR DESCRIPTION
**Pull request by Rich5**
This pull includes the beta implementation for a proposed hashcat API. The intent is to provide an interface that allows other developers to include hashcat in their projects with minimal changes to the core code base. See #9  for more details and history. 

I've also included documentation on the API design here: https://github.com/Rich5/oclHashcat/blob/master/docs/API.md

### CODE REVIEW

**Comment by jsteube** [comment]
This is a huge commit, many thanks! Actually there's not much I have to comment, just a few changes:

> make win64API win32API linux64API linux32API

Does that mean that there's no support for the native and/or osx target?

> include/CL/*

I saw you accidentially added the opencl-headers to the repository. Please remove them. We describe in BUILD.me how to install them.

> src/hashcatAPI.c

Two things here:
1. Can you please rename it to hashcat_api.c
2. Can you please use the format used describe in the contribution section on here? https://github.com/hashcat/oclHashcat That is like allman-style format etc.

**Comment by Rich5** [comment]
> Does that mean that there's no support for the native and/or osx target?

 I'll add support to the Make file for native install and do a few tests. This should be an easy addition.  

As for osx, I don't have access to a mac to do any testing. I don't think there is any reason why it wouldn't work though, but can't verify myself. 

> I saw you accidentially added the opencl-headers to the repository. Please remove them. We describe in BUILD.me how to install them.

Oops. I'll get those removed. 

> Can you please rename it to hashcat_api.c

No problem.

> Can you please use the format used describe in the contribution section on here? https://github.com/hashcat/oclHashcat That is like allman-style format etc.

I'll run `indent` on it to make sure it's formatted correctly. 

Should have most of this done by tonight or tomorrow.

**Comment by Rich5** [comment]
Doing some testing. I'll post here when it's ready.

**Comment by Rich5** [comment]
Ok. I'm done testing. Checked out good for me on the following systems:

Win7
Win8
Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux

**Comment by jsteube** [comment]
OK, something is odd. I made two tests and both failed :(
- Trying to run on windows. Compiled with win64API target. Result:

```
d:\tools\hashcat-3.00>hashcat64API
[*] Starting API Test.
[!] hashcat starting in the background
USAGE: [q]uit [S]tatus
sS
[ERROR] status update not available
Either hashcat has not fully started yet just wait a couple of seconds
 Or there is an arg error. Check your settings and use -DDEBUG flag.
```

I then waited for around a minute but nothing changed
- Compiling on linux fails:

```
root@sf:~/hashcat# make nativeAPI
gcc -D_POSIX -DLINUX -s -pipe -W -Wall -std=c99 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -O2 -DHAVE_HWMON -c -o obj/ext_OpenCL.NATIVE.o src/ext_OpenCL.c
gcc -D_POSIX -DLINUX -s -pipe -W -Wall -std=c99 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -O2 -DHAVE_HWMON -c -o obj/shared.NATIVE.o src/shared.c
gcc -D_POSIX -DLINUX -s -pipe -W -Wall -std=c99 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -O2 -DHAVE_HWMON -c -o obj/rp_kernel_on_cpu.NATIVE.o src/rp_kernel_on_cpu.c
gcc -D_POSIX -DLINUX -s -pipe -W -Wall -std=c99 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -O2 -DHAVE_HWMON -c -o obj/ext_ADL.NATIVE.o src/ext_ADL.c
gcc -D_POSIX -DLINUX -s -pipe -W -Wall -std=c99 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -O2 -DHAVE_HWMON -c -o obj/ext_nvapi.NATIVE.o src/ext_nvapi.c
gcc -D_POSIX -DLINUX -s -pipe -W -Wall -std=c99 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -O2 -DHAVE_HWMON -c -o obj/ext_nvml.NATIVE.o src/ext_nvml.c
gcc -D_POSIX -DLINUX -s -pipe -W -Wall -std=c99 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -O2 -DHAVE_HWMON -c -o obj/ext_xnvctrl.NATIVE.o src/ext_xnvctrl.c
gcc -D_POSIX -DLINUX -s -pipe -W -Wall -std=c99 -Iinclude/ -IOpenCL/ -Ideps/OpenCL-Headers/ -O2 -DHAVE_HWMON    -DAPI -lm -o hashcat src/hashcat.c src/hashcat_api.c obj/ext_OpenCL.NATIVE.o obj/shared.NATIVE.o obj/rp_kernel_on_cpu.NATIVE.o obj/ext_ADL.NATIVE.o obj/ext_nvapi.NATIVE.o obj/ext_nvml.NATIVE.o obj/ext_xnvctrl.NATIVE.o -lpthread -ldl -DCOMPTIME=1466620722 -DVERSION_TAG=\"v3.00-beta-253-g8e5004d\" -DINSTALL_FOLDER=\"/usr/local/bin\" -DSHARED_FOLDER=\"/usr/local/share/hashcat\" -DDOCUMENT_FOLDER=\"/usr/local/share/doc/hashcat\"
/tmp/ccNqs8FF.o: In function `hcapi_generate_commandline':
hashcat_api.c:(.text+0x2217): undefined reference to `log10'
hashcat_api.c:(.text+0x221c): undefined reference to `ceil'
hashcat_api.c:(.text+0x2740): undefined reference to `log10'
hashcat_api.c:(.text+0x2745): undefined reference to `ceil'
hashcat_api.c:(.text+0x2883): undefined reference to `log10'
hashcat_api.c:(.text+0x2888): undefined reference to `ceil'
hashcat_api.c:(.text+0x296e): undefined reference to `log10'
hashcat_api.c:(.text+0x2973): undefined reference to `ceil'
hashcat_api.c:(.text+0x2a4c): undefined reference to `log10'
hashcat_api.c:(.text+0x2a51): undefined reference to `ceil'
hashcat_api.c:(.text+0x2bec): undefined reference to `log10'
hashcat_api.c:(.text+0x2bf1): undefined reference to `ceil'
hashcat_api.c:(.text+0x2caa): undefined reference to `log10'
hashcat_api.c:(.text+0x2caf): undefined reference to `ceil'
hashcat_api.c:(.text+0x2ed3): undefined reference to `log10'
hashcat_api.c:(.text+0x2ed8): undefined reference to `ceil'
hashcat_api.c:(.text+0x2f91): undefined reference to `log10'
hashcat_api.c:(.text+0x2f96): undefined reference to `ceil'
hashcat_api.c:(.text+0x337e): undefined reference to `log10'
hashcat_api.c:(.text+0x3383): undefined reference to `ceil'
hashcat_api.c:(.text+0x3469): undefined reference to `log10'
hashcat_api.c:(.text+0x346e): undefined reference to `ceil'
hashcat_api.c:(.text+0x3524): undefined reference to `log10'
hashcat_api.c:(.text+0x3529): undefined reference to `ceil'
hashcat_api.c:(.text+0x35fd): undefined reference to `log10'
hashcat_api.c:(.text+0x3602): undefined reference to `ceil'
hashcat_api.c:(.text+0x3767): undefined reference to `log10'
hashcat_api.c:(.text+0x376c): undefined reference to `ceil'
hashcat_api.c:(.text+0x3822): undefined reference to `log10'
hashcat_api.c:(.text+0x3827): undefined reference to `ceil'
hashcat_api.c:(.text+0x41ef): undefined reference to `log10'
hashcat_api.c:(.text+0x41f4): undefined reference to `ceil'
hashcat_api.c:(.text+0x442f): undefined reference to `log10'
hashcat_api.c:(.text+0x4434): undefined reference to `ceil'
hashcat_api.c:(.text+0x44ef): undefined reference to `log10'
hashcat_api.c:(.text+0x44f4): undefined reference to `ceil'
hashcat_api.c:(.text+0x462f): undefined reference to `log10'
hashcat_api.c:(.text+0x4634): undefined reference to `ceil'
hashcat_api.c:(.text+0x46ef): undefined reference to `log10'
hashcat_api.c:(.text+0x46f4): undefined reference to `ceil'
hashcat_api.c:(.text+0x4baf): undefined reference to `log10'
hashcat_api.c:(.text+0x4bb4): undefined reference to `ceil'
hashcat_api.c:(.text+0x4d6f): undefined reference to `log10'
hashcat_api.c:(.text+0x4d74): undefined reference to `ceil'
hashcat_api.c:(.text+0x4e2f): undefined reference to `log10'
hashcat_api.c:(.text+0x4e34): undefined reference to `ceil'
hashcat_api.c:(.text+0x4eef): undefined reference to `log10'
hashcat_api.c:(.text+0x4ef4): undefined reference to `ceil'
hashcat_api.c:(.text+0x502f): undefined reference to `log10'
hashcat_api.c:(.text+0x5034): undefined reference to `ceil'
collect2: error: ld returned 1 exit status
make: *** [hashcatAPI] Error 1

```

I'm wondering. What's the reason to not pack it into a .so? I think that's what people expect from a true API and actually I should be pretty easy.

**Comment by Rich5** [comment]
Bah. Ok. The first error might be a result of the example I wrote. `hc.status_update()` returns 0 because of these checks:

```
if (data.devices_status == STATUS_INIT)
    return 0;
if (data.devices_status == STATUS_STARTING)
    return 0;
if (data.devices_status == STATUS_BYPASS)
    return 0;
```

The foreground thread seems to get hung because of getchar() I think. I'll have to write a better example. In the mean time if you give the hashcat process a chance to spin up and then try getting the status does it display? 

UPDATE: I also just thought of something. Check these lines starting at 3143 in the example. I bet they aren't pointing to the right example files: 

https://github.com/Rich5/oclHashcat/blob/master/src/hashcat_api.c#L3143

The second error is a result of the math library not being linked which I don't understand why that's happening. make `nativeAPI` should compile with this line that links the math library:

```
hashcatAPI:       src/hashcat.c src/hashcat_api.c $(NATIVE_OBJS)
    $(CC) $(CFLAGS_NATIVE)    -DAPI -lm -o $(BINARY_NATIVE) $^ $(LFLAGS_NATIVE) -DCOMPTIME=$(COMPTIME) -DVERSION_TAG=\"$(VERSION_TAG)\" -DINSTALL_FOLDER=\"$(INSTALL_FOLDER)\" -DSHARED_FOLDER=\"$(SHARED_FOLDER)\" -DDOCUMENT_FOLDER=\"$(DOCUMENT_FOLDER)\"

```

I'll have to troubleshoot more on this one because it was working earlier (I'm away from my lab until tomorrow).

Lastly, I agree I think packing into an .so would be ideal. I'm probably going to need some help with that though. I'm not the best Linux dev. If you need to deny this pull that's ok. I'll work on it more in the next few days as I get time.

**Comment by jsteube** [comment]
I'll reject this for now, but only because I want to have the repository clean when we fusion hashcat and oclHashcat into one. Otherwise this is getting more complicated than it needs to be. Don't worry, we'll add this after the release. This is great work.

**Comment by Rich5** [comment]
Sounds good. That makes sense. Let me know when you're ready to come back to this after the release.

**Comment by jsteube** [comment]
The fusion is done and I've refactored hashcat basically into libhashcat. The goal is it to make it even easier to call hashcat from 3rd party applications.

Please check out the hashcat-as-library branch, especially this main_shared.c demo: https://github.com/hashcat/hashcat/blob/hashcat-as-library/src/main_shared.c

Do you think you can modify your python bindings to this? I think your bindings should be easy to refactor, or at least I hope so. After that, you should create your own repository for the bindings. Maybe add some example code how to use it from python, like main_shared.c is.

**Comment by Rich5** [comment]
After just briefly reviewing, this looks awesome! I'll be able to dig deeper in the next few days. I think it will be pretty straight forward to adapt the python bindings to this, but I'll know more next week when I get back from travel. Thanks for taking the time to do this.

**Comment by Rich5** [comment]
The addition of events is really nice. Is there a way to get all the same status info as pressing "s" during a normal run? For example, I've seen people parse out the GPU temp to use as triggers in scripts. Are events intended to be used in this way? I'm my previous PR I was basically taking a snapshot of that type of information and storing for the user in a structure. Is that a feature that should be at this level? Seems like you have a well defined plan here so just let me know if you need me to work on some part or just test by adapting python bindings?

**Comment by jsteube** [comment]
> Is there a way to get all the same status info as pressing "s" during a normal run?

Absolutely, yes. As a proof you can see in main.c that the main.c itself is spawning the thread handling the prompt. I can see how important that it. There's always two ways to access the data. Either by accessing the hashcat_ctx data or by using an event. But for a status check (like speed and so on) an event would be unpractical, so you want to access it via hashcat_ctx. For example, if the user presses "s", it's the main thread handling it. You can follow it through main_outerloop_starting() -> thread_keypress() -> keypress() -> status_display() and from there, there's the code how to access the details

> Are events intended to be used in this way? 

Not for status. Events are useful for example if a hash was cracked.

> Seems like you have a well defined plan here so just let me know if you need me to work on some part or just test by adapting python bindings?

For the events, it's possible to add more event. At this point I've just add those which I needed to have the new main.c create the same output as original hashcat before refactoring. But it's possible you want some additional events. If you find some during your binding work, tell me and I'll add them. Note that everything is very new and it's possible I change this. Before you start writing the bindings you should wait for the release version. Or, if you start right now, I can't guarantee nothing changes.

Anyway I should close this as the original hashcat API is not what it will be in the future, plus I expect it to be in your own repository, which makes much more sense.

**Comment by Rich5** [comment]
Thanks again for taking the time to do this. I'm looking forward to testing it out

**Comment by Rich5** [comment]
I'm probably just missing this part, but one more question about accessing the status. It looks like all the information is stored in `hashcat_ctx`, and I understand that the `status_display` calculates and displays all the status, but how would that be accessed programmatically through the hashcatlib? Would I access `hashcat_ctx` directly? Previously, I ended up making a new function that copies the status and updates a structure when called. You can see it here:  https://github.com/Rich5/oclHashcat/blob/master/src/hashcat_api.c#L1897

`hcapi_status_update` was basically just a modified version of `status_display` that calculated and copied values. Is there a better way to do this now?

**Comment by jsteube** [comment]
Not yet, but we should develop a better version. What I'm talking is something like simplified getter functions for the status informations. For example get_device_speed(device_id) or so.  I'll write them, but can you tell me which type of getters are of use?

**Comment by Rich5** [comment]
I think developers would at least want to query for the information that is on the status screen. Here's a screenshot of the status info I thought would be useful previously. Maybe not all are necessary though for the first iteration.
img_20161015_125753

Is that helpful?  I can come up with a named list of those items if that's of more use.

**Comment by jsteube** [comment]
Hey @Rich5 

I think the version now is close to what you'd expect from an api. First, there's the following methods to control a running process:

```
int hashcat_session_pause (hashcat_ctx_t *hashcat_ctx)
int hashcat_session_resume (hashcat_ctx_t *hashcat_ctx)
int hashcat_session_bypass (hashcat_ctx_t *hashcat_ctx)
int hashcat_session_checkpoint (hashcat_ctx_t *hashcat_ctx)
int hashcat_session_quit (hashcat_ctx_t *hashcat_ctx)
```

Taken from here: https://github.com/hashcat/hashcat/blob/hashcat-as-library/include/hashcat.h#L12-L17

Basically the stuff you can see on the status prompt when you run the commandline. It's pretty self explaining I hope.

Next, I've added the following helper methods to read the status:

```
int     status_get_device_info_cnt            (const hashcat_ctx_t *hashcat_ctx);
int     status_get_device_info_active         (const hashcat_ctx_t *hashcat_ctx);
bool    status_get_skipped_dev                (const hashcat_ctx_t *hashcat_ctx, const int device_id);
char   *status_get_session                    (const hashcat_ctx_t *hashcat_ctx);
char   *status_get_status_string              (const hashcat_ctx_t *hashcat_ctx);
int     status_get_input_mode                 (const hashcat_ctx_t *hashcat_ctx);
char   *status_get_input_base                 (const hashcat_ctx_t *hashcat_ctx);
char   *status_get_input_mod                  (const hashcat_ctx_t *hashcat_ctx);
char   *status_get_input_charset              (const hashcat_ctx_t *hashcat_ctx);
char   *status_get_input_candidates_dev       (const hashcat_ctx_t *hashcat_ctx, const int device_id);
char   *status_get_hash_type                  (const hashcat_ctx_t *hashcat_ctx);
char   *status_get_hash_target                (const hashcat_ctx_t *hashcat_ctx);
int     status_get_digests_done               (const hashcat_ctx_t *hashcat_ctx);
int     status_get_digests_cnt                (const hashcat_ctx_t *hashcat_ctx);
double  status_get_digests_percent            (const hashcat_ctx_t *hashcat_ctx);
int     status_get_salts_done                 (const hashcat_ctx_t *hashcat_ctx);
int     status_get_salts_cnt                  (const hashcat_ctx_t *hashcat_ctx);
double  status_get_salts_percent              (const hashcat_ctx_t *hashcat_ctx);
double  status_get_msec_running               (const hashcat_ctx_t *hashcat_ctx);
double  status_get_msec_paused                (const hashcat_ctx_t *hashcat_ctx);
double  status_get_msec_real                  (const hashcat_ctx_t *hashcat_ctx);
char   *status_get_time_started_absolute      (const hashcat_ctx_t *hashcat_ctx);
char   *status_get_time_started_relative      (const hashcat_ctx_t *hashcat_ctx);
char   *status_get_time_estimated_absolute    (const hashcat_ctx_t *hashcat_ctx);
char   *status_get_time_estimated_relative    (const hashcat_ctx_t *hashcat_ctx);
u64     status_get_restore_point              (const hashcat_ctx_t *hashcat_ctx);
u64     status_get_restore_total              (const hashcat_ctx_t *hashcat_ctx);
double  status_get_restore_percent            (const hashcat_ctx_t *hashcat_ctx);
int     status_get_progress_mode              (const hashcat_ctx_t *hashcat_ctx);
double  status_get_progress_finished_percent  (const hashcat_ctx_t *hashcat_ctx);
u64     status_get_progress_done              (const hashcat_ctx_t *hashcat_ctx);
u64     status_get_progress_rejected          (const hashcat_ctx_t *hashcat_ctx);
double  status_get_progress_rejected_percent  (const hashcat_ctx_t *hashcat_ctx);
u64     status_get_progress_restored          (const hashcat_ctx_t *hashcat_ctx);
u64     status_get_progress_cur               (const hashcat_ctx_t *hashcat_ctx);
u64     status_get_progress_end               (const hashcat_ctx_t *hashcat_ctx);
u64     status_get_progress_ignore            (const hashcat_ctx_t *hashcat_ctx);
u64     status_get_progress_skip              (const hashcat_ctx_t *hashcat_ctx);
u64     status_get_progress_cur_relative_skip (const hashcat_ctx_t *hashcat_ctx);
u64     status_get_progress_end_relative_skip (const hashcat_ctx_t *hashcat_ctx);
double  status_get_hashes_msec_all            (const hashcat_ctx_t *hashcat_ctx);
double  status_get_hashes_msec_dev            (const hashcat_ctx_t *hashcat_ctx, const int device_id);
double  status_get_hashes_msec_dev_benchmark  (const hashcat_ctx_t *hashcat_ctx, const int device_id);
double  status_get_exec_msec_all              (const hashcat_ctx_t *hashcat_ctx);
double  status_get_exec_msec_dev              (const hashcat_ctx_t *hashcat_ctx, const int device_id);
char   *status_get_speed_sec_all              (const hashcat_ctx_t *hashcat_ctx);
char   *status_get_speed_sec_dev              (const hashcat_ctx_t *hashcat_ctx, const int device_id);
int     status_get_cpt_cur_min                (const hashcat_ctx_t *hashcat_ctx);
int     status_get_cpt_cur_hour               (const hashcat_ctx_t *hashcat_ctx);
int     status_get_cpt_cur_day                (const hashcat_ctx_t *hashcat_ctx);
double  status_get_cpt_avg_min                (const hashcat_ctx_t *hashcat_ctx);
double  status_get_cpt_avg_hour               (const hashcat_ctx_t *hashcat_ctx);
double  status_get_cpt_avg_day                (const hashcat_ctx_t *hashcat_ctx);
char   *status_get_cpt                        (const hashcat_ctx_t *hashcat_ctx);
char   *status_get_hwmon_dev                  (const hashcat_ctx_t *hashcat_ctx, const int device_id);
```

Taken from here: https://github.com/hashcat/hashcat/blob/hashcat-as-library/include/status.h#L19-L73

Also, I've rewritten the status_display() function (that is what the commandline tool uses which is why it's in terminal.c) to use the same helper functions. The refactored status_display is here and can be used as an example code:  https://github.com/hashcat/hashcat/blob/hashcat-as-library/src/terminal.c#L612-L783

I'll refactor status_benchmark() and status_display_machine_readable() next, but that shouldn't interfere with your implementation. Note this stuff is still not in a released state, but your comments on this will be important, especially since you're actually writing the bindings and you will notice problems soon (if there are any).

**Comment by dropdeadfu** [comment]
awesome!

**Comment by Rich5** [comment]
Wow, thanks @jsteube 

With this foundation in place I think I'm going to rewrite the python bindings as a native Python extension as opposed to using the ctypes library in Python. Should be pretty straight forward and faster, but I'll let you know as I get into it. My plan is to start this week. I'll post comments here as they come up.

**Comment by jsteube** [comment]
Note that I've made a little change. The new typical call scenario is now this:
- hashcat_init 
- hashcat_session_init 
- hashcat_session_execute
- hashcat_session_destroy
- hashcat_destroy

So I've added that middle layer _session_. The reason is that in case you do not want to actually execute some attack but only check for like OpenCL devices available, the call to session_init() is enough.

**Comment by Rich5** [comment]
@jsteube so I was finally able to make a lot of progress on the Python bindings. If fact, a lot of the work is done for a Python 2.7 extension (the main part of the code is here temporarily if you're interested - https://gist.github.com/Rich5/a97747b91e1066f5d273dc1a6d8fc51b), but the one issue I'm running into is dependencies for libhashcat.so.

It looks like, by default, hashcat looks for dependencies relative to it's current working directory. Is there an easy way to specific that is should look somewhere else? For example, we move libhashcat.so to /usr/lib, but it's configured to look for all dependencies in /usr/local/share or something like that?  

UPDATE: Actually I think I may be able to specify an rpath when I compile the extension. If that works I'll have an branch up on the pyhashcat repo this week.

**Pull request closed without merging**
