### PR TITLE
GitHub workflow for pushing or creating pull request

### PR DESCRIPTION
**Pull request by ventaquil**
Workflow to build application after pushing or creating pull request for `master` branch.

As you can see this workflow builds application on Windows, Ubuntu and MacOS.

Some extra steps (e.g. with checking code style) can be added.

### CODE REVIEW

**Comment by ventaquil** [comment]
Another one reason to move to GH Actions? 🙃 

https://ci.appveyor.com/project/jsteube/hashcat/builds/43762450/job/srnt2ryxj484q651

**Comment by jsteube** [comment]
Let's try and see what happens :) Is there any way to see results before merging?

**Comment by ventaquil** [comment]
You can check them in my repository - https://github.com/ventaquil/hashcat/pull/1.

When you enter into _Actions_ you will see also buggy commit (commited to `master`).

I added also `shared` strategy to build binary with `SHARED=0` and `SHARED=1` env variables.

Currently all actions will be stopped when error occurs - as far as I know it can be changed.

**Comment by ventaquil** [comment]
Another cool feature - after creating a tag tests will be started. Currently all of jobs will fail because of GH-3337.

**Comment by jsteube** [comment]
I understand. This is like a GitHub internal replacement for Appveyor? It supports Windows, Ubuntu and MacOS? From your repository I can see that Windows was canceled. Is it not working?

**Comment by ventaquil** [comment]
That's it, GitHub Actions is GitHub builtin CI/CD system. It supports MacOS, Windows, Ubuntu and self-hosted runners.

I added option to do not stop other jobs when one fails - see https://github.com/ventaquil/hashcat/actions/runs/2549088867.

However I noticed that Windows runners don't have `iconv` library. I will try to fix it.

**Comment by jsteube** [comment]
We had many problem with Appveyor in the past. I think @philsmd also would like to see it being replaced, right?

**Comment by ventaquil** [comment]
Status of this workflow:
* The workflow will run when new commits will be pushed to `master` branch or when someone will create a PR.
* The workflow will run when new tag `v*` will appear.
* The workflow will run only when sources from `OpenCL/`, `include/` or `src/` are changed as well as tools from `tools/`.
* During the workflow code will be build with static and shared linking options.
* Only latest Ubuntu and MacOS images are used - Windows one is lack of iconv development files.

I opened discussion to add support for iconv on Windows image but will see the result - https://github.com/actions/virtual-environments/discussions/5814.

**Comment by philsmd** [comment]
well, I have at least nothing against replacing it (`Appveyor`) !

If this works better for us, I'm very happy with this change.

That said, I am also not very familiar with `Workflow for GitHub Actions` so not sure if my opinion counts too much here.

We could/should at least try it, I guess.

**Comment by ventaquil** [comment]
Issues like this GH-3256 can be done with extra workflows (possibly easy to do with [actions/flatpak-builder](https://github.com/marketplace/actions/flatpak-builder)).

**Comment by mdawsonuk** [comment]
Throwing in my two cents here, GitHub actions is super super powerful. You could also add artifacts so that you can download the compiled build of hashcat for that commit after the tests are also done. 

`actions/upload-artifact@v3` is what you'd want to use to upload after zipping up the executables

**Comment by ventaquil** [comment]
Hey @mdawsonuk

Thank you for your comment. I am not an expert in GitHub Actions so any suggestions/recommendations are welcome here! I will try to deal with [`actions/upload-artifact`](https://github.com/actions/upload-artifact) in my spare time and add proper commit.

**Comment by mdawsonuk** [comment]
I can take a look shortly and suggest the extra job to add to the YAML file if you would like?

**Comment by ventaquil** [comment]
If you have any experience and you can make proper changes I think that you can create PR to [`github-workflow`](https://github.com/ventaquil/hashcat/tree/github-workflow) branch in my repo [`ventaquil/hashcat`](https://github.com/ventaquil/hashcat).

As far as I know there is no other way to add your changes to this PR.

Thank you!

**Comment by mdawsonuk** [comment]
Alright I've got the upload artifact functionality working, ~~my concern is that the hashcat executable itself doesn't appear to be collected correctly as an artifact~~, as it's not being included with the zipped artifact. I'll have the PR over to you shortly

Edit: I'm stupid, `hashcat` **obviously** won't be picked up by the wildcard `hashcat.*`

**Comment by mdawsonuk** [comment]
@ventaquil ready for merging https://github.com/ventaquil/hashcat/pull/5

**Comment by mdawsonuk** [comment]
Just thinking for Windows builds, as the windows-latest image comes with WSL pre-installed, it might be a good idea to use WSL to build Hashcat for Windows, rather than screwing around with MSYS2 or Cygwin

**Comment by ventaquil** [comment]
@mdawsonuk I have tried to add `windows-latest` runner but there is lack of iconv library - see https://github.com/ventaquil/hashcat/runs/7075487788.

I don't know how to add it properly. I am not sure that WSL can be a solution but you can try to do it.

**Comment by mdawsonuk** [comment]
I use WSL for my local Windows dev - at the very least it's a good work around for no iconv

**Comment by mdawsonuk** [comment]
Can confirm that WSL building (in line with the hashcat documentation) works without issue 👍🏻

**Comment by ventaquil** [comment]
Instead of WSL building I prepared configuration with MSYS2. It's building Hashcat and working very well.

Thanks @mdawsonuk for idea with artifacts 👍

**Comment by ventaquil** [comment]
@jsteube @philsmd you can check example result here https://github.com/ventaquil/hashcat/actions/runs/2673637097.

**Comment by mdawsonuk** [comment]
> Another cool feature - after creating a tag tests will be started. Currently all of jobs will fail because of [GH-3337](https://github.com/hashcat/hashcat/issues/3337).

Are we actually running tests? As far as I'm aware, we're not. 

I'm also a proponent of smaller PRs so perhaps we could get this PR merged and then add running tests in a separate PR (I'm more than happy to work on that myself)

**Comment by ventaquil** [comment]
> > Another cool feature - after creating a tag tests will be started. Currently all of jobs will fail because of [GH-3337](https://github.com/hashcat/hashcat/issues/3337).
> 
> Are we actually running tests? As far as I'm aware, we're not.

Nope but shared binary building failed before (fixed in GH-3337).

> I'm also a proponent of smaller PRs so perhaps we could get this PR merged and then add running tests in a separate PR (I'm more than happy to work on that myself)

Totally agree, I am waiting for core team accept and merge. Then future work can be done.

However I am afraid that running tests will be impossible without self-hosted runners.

I am thinking about automatic issues/PRs labeling (or even closing), building release packages and adding archives to new releases and so on.

**Comment by mdawsonuk** [comment]
> However I am afraid that running tests will be impossible without self-hosted runners.

How so? 

> I am thinking about automatic issues/PRs labeling (or even closing), building release packages and adding archives to new releases and so on.

Yes these are all great ideas

**Comment by ventaquil** [comment]
> > However I am afraid that running tests will be impossible without self-hosted runners.
> 
> How so?

As far as I know provided runners do not have support for GPUs (so we cannot use CUDA or OpenCL) - see [GitHub Actions / Supported runners and hardware resources](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources).

GPU support can be achieved in self-hosted runners - see [GitHub Actions / Using self-hosted runners in workflow](https://docs.github.com/en/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow#using-custom-labels-to-route-jobs). Without those runners the only possible solution is to use PoCL - it should be enough.

**Comment by mdawsonuk** [comment]
> As far as I know provided runners do not have support for GPUs (so we cannot use CUDA or OpenCL) - see [GitHub Actions / Supported runners and hardware resources](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources).
> 
> GPU support can be achieved in self-hosted runners - see [GitHub Actions / Using self-hosted runners in workflow](https://docs.github.com/en/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow#using-custom-labels-to-route-jobs). Without those runners the only possible solution is to use PoCL - it should be enough.

I believe support for this has been very recently added https://github.com/github/roadmap/issues/505

**Comment by mdawsonuk** [comment]
Just wondering as an aside, maybe the artifact names should be lowercase? A bit more in line with common naming conventions.

**Comment by ventaquil** [comment]
@mdawsonuk by default `runner.os` returns `Windows`, `Linux` or `macOS` so I chose to use Pascal-case here.

It looks complicated to change case convention since there is no default `lowercase` function - github-community/community#10553.

**Comment by mdawsonuk** [comment]
> @mdawsonuk by default `runner.os` returns `Windows`, `Linux` or `macOS` so I chose to use Pascal-case here.
> 
> 
> 
> It looks complicated to change case convention since there is no default `lowercase` function - github-community/community#10553.

I thought the same initially but then it's a different build step for each OS, so actually using runner.os is redundant?

**Comment by ventaquil** [comment]
> I thought the same initially but then it's a different build step for each OS, so actually using runner.os is redundant?

Ah yeah, my fault. I made copy-paste and `runner.os` is not required anymore. I will prepare commit fix.

**Comment by jsteube** [comment]
OK this is completely new territory for me, too. Let's see how it works out :)

**Comment by ventaquil** [comment]
Thanks for merge, I hope that actions will be useful for everyone 👍

**Comment by ventaquil** [comment]
I looks that it works quite okay - https://github.com/hashcat/hashcat/actions/runs/2719841951.

**Comment by jsteube** [comment]
Looks good, yeah. Wondering if we could make windows work. The problem is only the iconv? Is there any way to trigger the test offline (on my dev system for instance)?

**Comment by ventaquil** [comment]
Hey @jsteube

Windows jobs are looking fine imho (with big thanks for help to @mdawsonuk).

Jobs

**Comment by ventaquil** [comment]
Also you can take a look at [nektos/act](https://github.com/nektos/act) to run workflow locally.

**Pull request merged**
