### PR TITLE
Add OSX HW Monitor initial support (2021)

### PR DESCRIPTION
**Pull request by matrix**
from #2085

### CODE REVIEW

**Comment by matrix** [comment]
```
$ ./hashcat -m 0 8743b52063cd84097a65d1633f5c74f5 example.dict -a6 ?a?a?a?a -D1,2
hashcat (v6.2.1-165-gbc4ce4cbe+) starting...

* Device #2: Apple's OpenCL drivers (GPU) are known to be unreliable.
             You have been warned.

OpenCL API (OpenCL 1.2 (May  7 2020 00:10:14)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz, 8128/8192 MB (2048 MB allocatable), 4MCU
* Device #2: Iris, 1472/1536 MB (384 MB allocatable), 40MCU

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Optimizers applied:
* Zero-Byte
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Hash
* Single-Salt
* Raw-Hash

ATTENTION! Pure (unoptimized) backend kernels selected.
Pure kernels can crack longer passwords, but drastically reduce performance.
If you want to switch to optimized kernels, append -O to your commandline.
See the above message to find out about the exact limits.

Watchdog: Temperature abort trigger set to 100c

Host memory required for this attack: 346 MB

Dictionary cache hit:
* Filename..: example.dict
* Passwords.: 128416
* Bytes.....: 1069601
* Keyspace..: 10459563460000

The wordlist or mask that you are using is too small.     
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.           

[s]tatus [p]ause [b]ypass [c]heckpoint [f]inish [q]uit => s

Session..........: hashcat
Status...........: Running
Hash.Name........: MD5
Hash.Target......: 8743b52063cd84097a65d1633f5c74f5
Time.Started.....: Sat Jun 12 20:30:31 2021 (43 secs)
Time.Estimated...: Mon Jun 14 04:16:49 2021 (1 day, 7 hours)
Kernel.Feature...: Pure Kernel
Guess.Base.......: File (example.dict), Left Side
Guess.Mod........: Mask (?a?a?a?a) [4], Right Side
Guess.Queue.Base.: 1/1 (100.00%)
Guess.Queue.Mod..: 1/1 (100.00%)
Speed.#1.........:  6813.6 kH/s (0.72ms) @ Accel:128 Loops:256 Thr:1 Vec:4
Speed.#2.........: 84635.0 kH/s (10.11ms) @ Accel:8 Loops:8 Thr:512 Vec:1
Speed.#*.........: 91448.6 kH/s
Recovered........: 0/1 (0.00%) Digests
Progress.........: 4019933248/10459563460000 (0.04%)
Rejected.........: 0/4019933248 (0.00%)
Restore.Point....: 0/128416 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:13818112-13818368 Iteration:0-256
Restore.Sub.#2...: Salt:0 Amplifier:28512-28520 Iteration:0-8
Candidate.Engine.: Device Generator
Candidates.#1....: 0;phd -> 00001234KYP0
Candidates.#2....: 00001478rlin -> zzzzzzzzzzziwov
Hardware.Mon.#1..: Temp: 81c Fan: 35%
Hardware.Mon.#2..: Temp: 96c Fan: 35%
```

**Comment by jsteube** [comment]
Do you know if this will work on all apple devices CPU and GPU? Is that IOkit package installed by default?

**Comment by matrix** [comment]
As for the parent PR, it is not tested on Apple multi-gpu systems. For the rest it should go :)
For IOkit, yes, it is present by default.

**Comment by jsteube** [comment]
I received test from some other computer. Please have a look:

```
hashcat (v6.2.2-9-g3119525ea+) starting...

* Device #2: Apple's OpenCL drivers (GPU) are known to be unreliable.
             You have been warned.

OpenCL API (OpenCL 1.2 (Feb 28 2021 03:51:16)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Xeon(R) W-3223 CPU @ 3.50GHz, 32704/32768 MB (8192 MB allocatable), 16MCU
* Device #2: AMD Radeon Pro W5700X Compute Engine, 16304/16368 MB (4092 MB allocatable), 40MCU

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates

Optimizers applied:
* Zero-Byte
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Hash
* Single-Salt
* Raw-Hash

ATTENTION! Pure (unoptimized) backend kernels selected.
Pure kernels can crack longer passwords, but drastically reduce performance.
If you want to switch to optimized kernels, append -O to your commandline.
See the above message to find out about the exact limits.

Watchdog: Temperature abort trigger set to 100c

Host memory required for this attack: 706 MB

Dictionary cache hit:
* Filename..: example.dict
* Passwords.: 128416
* Bytes.....: 1069601
* Keyspace..: 10459563460000

The wordlist or mask that you are using is too small.     
This means that hashcat cannot use the full parallel power of your device(s).
Unless you supply more work, your cracking speed will drop.
For tips on supplying more work, see: https://hashcat.net/faq/morework

Approaching final keyspace - workload adjusted.           

[s]tatus [p]ause [b]ypass [c]heckpoint [f]inish [q]uit => s

Session..........: hashcat
Status...........: Running
Hash.Name........: MD5
Hash.Target......: 8743b52063cd84097a65d1633f5c74f5
Time.Started.....: Fri Jun 18 09:54:42 2021 (7 secs)
Time.Estimated...: Fri Jun 18 10:55:36 2021 (1 hour, 0 mins)
Kernel.Feature...: Pure Kernel
Guess.Base.......: File (example.dict), Left Side
Guess.Mod........: Mask (?a?a?a?a) [4], Right Side
Guess.Queue.Base.: 1/1 (100.00%)
Guess.Queue.Mod..: 1/1 (100.00%)
Speed.#1.........: 68155.6 kH/s (2.92ms) @ Accel:256 Loops:256 Thr:1 Vec:4
Speed.#2.........:  2794.2 MH/s (12.39ms) @ Accel:64 Loops:512 Thr:64 Vec:1
Speed.#*.........:  2862.0 MH/s
Recovered........: 0/1 (0.00%) Digests
Progress.........: 19616034304/10459563460000 (0.19%)
Rejected.........: 0/19616034304 (0.00%)
Restore.Point....: 0/128416 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:590336-590592 Iteration:0-256
Restore.Sub.#2...: Salt:0 Amplifier:150016-150528 Iteration:0-512
Candidate.Engine.: Device Generator
Candidates.#1....: 00qNI -> 0172<8,m
Candidates.#2....: 017251547tLTT -> zzzzzzzzzzzKQEE
Hardware.Mon.#1..: Temp: 31c Fan:  0%
Hardware.Mon.#2..: Temp: 35c Fan:  0%
```

I believe the temperature is good, but the Fan speed looks invalid. Any Idea what's the problem?

hw.model: MacPro7,1

**Comment by matrix** [comment]
With my macbook pro, fan speed indicator is shared (only 1 sensor). I need wait more than 7 seconds to see changes.
I see you have an AMD gpu, if you want we can do some tests during the weekend to understand this patch work well also on this system.

**Comment by jsteube** [comment]
OK, I have access to the system

**Comment by jsteube** [comment]
I think the problem is somewhere here:

```
      if (strcmp(val.dataType, DATATYPE_FPE2) == 0)
```

Value in val.dataType is "flt".

Update:

I have added some stuff like this:

```
      if (strcmp(val.dataType, "flt ") == 0)
      {
        *ret = *(float *) val.bytes;

        return true;
      }
```

Is funny, one needs to add a space after "flt". API using strings. With space. No comment.

Anyway, one of the fans now report value:

actual_speed: 499.334229
minimum_speed: 500.000000
maximum_speed: 1254.000000

spindump reports the same value. However is not transported to status view.

Could be here:

```
      rpm = actual_speed - minimum_speed;
      if (rpm < 0.f) rpm = 0.f;
```

I think logic is not valid, see above values. Maybe minimum_speed has  to be interpreted not as zero point. Maybe it just says the fan is always running 500/1254 and can run no lower. So we should use actual_speed/maximum_speed as value.

**Comment by jsteube** [comment]
Something is not correct:

```
Hardware.Mon.#1..: Temp: 37c Fan: 41%
Hardware.Mon.#2..: Temp: 52c Fan: 41%
```

It uses the same fan for both devices. Is not coincidence I updated several times.

**Pull request merged**
